//! Extract game data from the original ROM (US Falzar,
//! `MEGAMAN6_FXXBR6E`).
//!
//! Usage:
//! - `bn6-extract <rom> [out-dir]`: the engine's tables as Rust source
//!   (out-dir defaults to crates/bn6-battle/src/data);
//! - `bn6-extract assets <rom> <sound-bank>`: the sound bank bn6-audio plays
//!   (see assets.rs);
//! - `bn6-extract graphics <rom> <out-dir>`: the graphics bundle
//!   bn6-frontend draws with (see graphics.rs);
//! - `bn6-extract content <rom> <pack-dir>`: the graphics and sound as a
//!   content pack of open, editable formats (see content.rs).
//!
//! The sound bank, the graphics and content packs are the game's own data:
//! write them outside version control (data/sound/, data/graphics/ and
//! data/content/ are ignored).

mod assets;
mod content;
mod graphics;
mod hud;

use std::fmt::Write as _;
use std::path::PathBuf;

pub(crate) struct Rom(Vec<u8>);

impl Rom {
    fn u8(&self, a: u32) -> u8 {
        self.0[(a & 0x01FF_FFFF) as usize]
    }
    fn u16(&self, a: u32) -> u16 {
        u16::from_le_bytes([self.u8(a), self.u8(a + 1)])
    }
    fn bytes(&self, a: u32, n: usize) -> &[u8] {
        let o = (a & 0x01FF_FFFF) as usize;
        &self.0[o..o + n]
    }
}

/// The game's text encoding for bytes 0x00-0xDF (from the disassembly's charmap).
const CHARSET: [&str; 0xE0] = [
    "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E",
    "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U",
    "V", "W", "X", "Y", "Z", "*", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
    "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
    "[RV]", "[BX]", "[EX]", "[SP]", "[FZ]", "ウ", "ア", "イ", "オ", "エ", "ケ", "コ", "カ", "ク", "キ", "セ",
    "サ", "ソ", "シ", "ス", "テ", "ト", "ツ", "タ", "チ", "ネ", "ノ", "ヌ", "ナ", "ニ", "ヒ", "ヘ",
    "ホ", "ハ", "フ", "ミ", "マ", "メ", "ム", "モ", "ヤ", "ヨ", "ユ", "ロ", "ル", "リ", "レ", "ラ",
    "ン", "熱", "斗", "ワ", "ヲ", "ギ", "ガ", "ゲ", "ゴ", "グ", "ゾ", "ジ", "ゼ", "ズ", "ザ", "デ",
    "ド", "ヅ", "ダ", "ヂ", "ベ", "ビ", "ボ", "バ", "ブ", "ピ", "パ", "ペ", "プ", "ポ", "ゥ", "ァ",
    "ィ", "ォ", "ェ", "ュ", "ヴ", "ッ", "ョ", "ャ", "-", "×", "=", ":", "%", "?", "+", "█",
    "[bat]", "ー", "!", "&", ",", "゜", ".", "・", ";", "'", "\"", "~", "/", "(", ")", "｢",
    "｣", " ", "_", "[z]", "[L]", "[B]", "[R]", "[A]", "あ", "い", "け", "く", "き", "こ", "か", "せ",
    "そ", "す", "さ", "し", "つ", "と", "て", "た", "ち", "ね", "の", "な", "ぬ", "に", "へ", "ふ",
    "ほ", "は", "ひ", "め", "む", "み", "も", "ま", "ゆ", "よ", "や", "る", "ら", "り", "ろ", "れ",
];

/// Decode string `index` of a text archive (u16 offsets, then strings).
fn archive_string(rom: &Rom, archive: u32, index: u32) -> String {
    let mut a = archive + rom.u16(archive + 2 * index) as u32;
    let mut s = String::new();
    loop {
        let b = rom.u8(a) as usize;
        if b >= CHARSET.len() {
            return s;
        }
        s.push_str(CHARSET[b]);
        a += 1;
    }
}

fn chip_name(rom: &Rom, id: u32) -> String {
    const NAMES0: u32 = 0x086E_A94C;
    const NAMES1: u32 = 0x086E_B354;
    if id <= 0xFF { archive_string(rom, NAMES0, id) } else { archive_string(rom, NAMES1, id & 0xFF) }
}

const HEADER: &str = "// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.\n\n";

/// The chip data table (ChipDataArr, 0x2C-byte records).
fn chips(rom: &Rom) -> String {
    const TABLE: u32 = 0x0802_1DA8;
    const RECORD: u32 = 0x2C;
    const COUNT: u32 = 411;
    let mut out = String::from(HEADER);
    out.push_str("use super::{ChipClass, ChipCode, ChipData, ChipFlags, Element};\n\n");
    writeln!(out, "pub static CHIPS: [ChipData; {COUNT}] = [").unwrap();
    for id in 0..COUNT {
        let r = TABLE + id * RECORD;
        let codes: Vec<String> =
            rom.bytes(r, 4).iter().filter(|&&c| c != 0xFF).map(|c| format!("ChipCode({c})")).collect();
        let name = chip_name(rom, id);
        let u32at = |a: u32| u32::from_le_bytes(rom.bytes(a, 4).try_into().unwrap());
        writeln!(
            out,
            "    ChipData {{ name: {name:?}, codes: &[{}], element: Element::{}, rarity: {}, family: {}, class: ChipClass::{}, mb: {}, flags: ChipFlags({:#04x}), hit_param: {}, action: {:#04x}, subtype: {}, beast_lockon: {}, params: {:#010x}, lockout: {}, lib_index: {}, flags2: {:#04x}, lockon_mode: {}, sort_key: {:#06x}, damage: {}, library_no: {}, slotin_max: {}, dark_subst: {} }}, // {id:#05x}",
            codes.join(", "),
            ["Null", "Fire", "Aqua", "Elec", "Wood"][rom.u8(r + 4) as usize],
            rom.u8(r + 5),
            rom.u8(r + 6),
            ["Standard", "Mega", "Giga", "Special", "ProgramAdvance"][rom.u8(r + 7) as usize],
            rom.u8(r + 8),
            rom.u8(r + 9),
            rom.u8(r + 0xA),
            rom.u8(r + 0xB),
            rom.u8(r + 0xC),
            // +0x0D and +0x0E have no reader in the game; not extracted.
            rom.u8(r + 0xF),
            u32at(r + 0x10),
            rom.u8(r + 0x14),
            rom.u8(r + 0x15),
            rom.u8(r + 0x16),
            rom.u8(r + 0x17),
            rom.u16(r + 0x18),
            rom.u16(r + 0x1A),
            rom.u16(r + 0x1C),
            rom.u8(r + 0x1E),
            rom.u8(r + 0x1F),
        )
        .unwrap();
    }
    out.push_str("];\n");
    out
}

/// HUD banner tables: which banners hold until removed (types 2 and 4 in
/// `pt_801EF84` records, byte 2) and the per-navi netbattle win/lose
/// banners.
fn banners(rom: &Rom) -> String {
    let mut out = String::from(HEADER);
    writeln!(out, "use super::BannerId;\n").unwrap();
    let base = 0x0801_EF84;
    let mut holds = Vec::new();
    loop {
        let p = u32::from_le_bytes(rom.bytes(base + 4 * holds.len() as u32, 4).try_into().unwrap());
        if !(0x0800_0000..0x0900_0000).contains(&p) {
            break;
        }
        holds.push(matches!(rom.u8(p + 2), 2 | 4));
    }
    writeln!(out, "/// Whether a banner stays up until removed, by banner id / 4.").unwrap();
    writeln!(out, "pub static BANNER_HOLDS: [bool; {}] = {:?};", holds.len(), holds).unwrap();
    let ids = |a: u32| -> String {
        let v: Vec<String> = rom.bytes(a, 12).iter().map(|b| format!("BannerId({b:#04x})")).collect();
        v.join(", ")
    };
    writeln!(out, "/// Netbattle win banner by navi (`byte_800A8EC`).").unwrap();
    writeln!(out, "pub static WIN_BANNERS: [BannerId; 12] = [{}];", ids(0x0800_A8EC)).unwrap();
    writeln!(out, "/// Netbattle lose banner by navi (`byte_800A8C8`).").unwrap();
    writeln!(out, "pub static LOSE_BANNERS: [BannerId; 12] = [{}];", ids(0x0800_A8C8)).unwrap();
    out
}

pub(crate) fn u32at(rom: &Rom, a: u32) -> u32 {
    u32::from_le_bytes(rom.bytes(a, 4).try_into().unwrap())
}

/// IWRAM code/data is a copy of the ROM at 0x081D6000.
fn iwram(a: u32) -> u32 {
    a - 0x0300_5B00 + 0x081D_6000
}

/// Field tables: panel layouts, per-panel constants, panel type flags and
/// movement rules.
fn field(rom: &Rom) -> String {
    const TYPES: [&str; 13] = [
        "Missing", "Broken", "Normal", "Cracked", "Poison", "Holy", "Grass", "Ice", "Volcano", "RoadUp", "RoadDown",
        "RoadLeft", "RoadRight",
    ];
    let mut out = String::from(HEADER);
    writeln!(out, "use super::{{PanelCondition, PanelOffset}};").unwrap();
    writeln!(out, "use crate::field::PanelType::{{self, *}};\n").unwrap();
    // `word_800D730`: one u32 per row (y 1..3), a nibble per column (x 1..6).
    let n = (0x0800_E24C - 0x0800_D730) / 12;
    writeln!(out, "/// Panel types per layout, [y - 1][x - 1] over the playable 6x3.").unwrap();
    writeln!(out, "pub static PANEL_LAYOUTS: [[[PanelType; 6]; 3]; {n}] = [").unwrap();
    for i in 0..n {
        let rows: Vec<String> = (0..3)
            .map(|y| {
                let w = u32at(rom, 0x0800_D730 + 12 * i + 4 * y);
                let row: Vec<&str> = (0..6).map(|x| TYPES[((w >> (4 * x)) & 0xF) as usize]).collect();
                format!("[{}]", row.join(", "))
            })
            .collect();
        writeln!(out, "    [{}], // {i:#04x}", rows.join(", ")).unwrap();
    }
    writeln!(out, "];").unwrap();
    let grid = |a: u32| -> String {
        let rows: Vec<String> = (0..5)
            .map(|y| {
                let row: Vec<String> = (0..8).map(|x| (rom.u8(a + 8 * y + x) != 0).to_string()).collect();
                format!("[{}]", row.join(", "))
            })
            .collect();
        rows.join(", ")
    };
    writeln!(out, "/// Whether each panel is drawn at the start of a round, [y][x] (`byte_800C590`).").unwrap();
    writeln!(out, "pub static PANEL_VISIBLE: [[bool; 8]; 5] = [{}];", grid(0x0800_C590)).unwrap();
    writeln!(out, "/// Whether each panel draws its front edge, [y][x] (`byte_800C5B8`).").unwrap();
    writeln!(out, "pub static PANEL_FRONT_EDGE: [[bool; 8]; 5] = [{}];", grid(0x0800_C5B8)).unwrap();
    let types: Vec<String> = (0..13).map(|i| format!("{:#07x}", u32at(rom, iwram(0x0300_7924) + 4 * i))).collect();
    writeln!(out, "/// Flag bits each panel type contributes, by `PanelType` (`word_3007924`).").unwrap();
    writeln!(out, "pub static PANEL_TYPE_FLAGS: [u32; 13] = [{}];", types.join(", ")).unwrap();
    let rules = |a: u32| -> String {
        let r: Vec<String> = (0..2)
            .map(|floor| {
                let sides: Vec<String> = (0..2)
                    .map(|side| {
                        let e = a + 16 * floor + 8 * side;
                        format!("PanelCondition {{ require: {:#x}, forbid: {:#010x} }}", u32at(rom, e), u32at(rom, e + 4))
                    })
                    .collect();
                format!("[{}]", sides.join(", "))
            })
            .collect();
        r.join(", ")
    };
    writeln!(out, "/// What a panel must be to step onto, by [floor-free (AirShoes or standing off solid ground)][alliance] (`tbl_800E660`).").unwrap();
    writeln!(out, "pub static STEP_RULES: [[PanelCondition; 2]; 2] = [{}];", rules(0x0800_E660)).unwrap();
    writeln!(out, "/// Step rules in dash mode (`byte_8010388`).").unwrap();
    writeln!(out, "pub static DASH_STEP_RULES: [[PanelCondition; 2]; 2] = [{}];", rules(0x0801_0388)).unwrap();
    writeln!(out, "/// Step rules ignoring panel ownership (`byte_800E6C8`).").unwrap();
    writeln!(out, "pub static ANY_SIDE_STEP_RULES: [[PanelCondition; 2]; 2] = [{}];", rules(0x0800_E6C8)).unwrap();
    let road: Vec<String> = (0..4)
        .map(|i| format!("PanelOffset {{ dx: {}, dy: {} }}", rom.u8(0x0800_E538 + 4 * i) as i8, rom.u8(0x0800_E539 + 4 * i) as i8))
        .collect();
    writeln!(out, "/// Road conveyor direction for RoadUp, RoadDown, RoadLeft, RoadRight (`byte_800E538`).").unwrap();
    writeln!(out, "pub static ROAD_DIRECTIONS: [PanelOffset; 4] = [{}];", road.join(", ")).unwrap();
    let _ = TYPES;
    out
}

/// Collision tables: type flags, region shapes, element weaknesses.
fn collision(rom: &Rom) -> String {
    let mut out = String::from(HEADER);
    writeln!(out, "use super::{{PanelCondition, PanelOffset}};\n").unwrap();
    writeln!(out, "/// Collision type flags [alliance 0, alliance 1] by index (`byte_8019C7C`).").unwrap();
    writeln!(out, "pub static COLLISION_TYPES: [[u32; 2]; 89] = [").unwrap();
    for i in 0..89 {
        let a = 0x0801_9C7C + 8 * i;
        writeln!(out, "    [{:#010x}, {:#010x}], // {i:#04x}", u32at(rom, a), u32at(rom, a + 4)).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out, "/// Region shapes: the panels a hit covers, relative to its panel, dx toward the facing side (`PanelOffsetListsPointerTable`).").unwrap();
    writeln!(out, "pub static REGIONS: [&[PanelOffset]; 47] = [").unwrap();
    for i in 0..47 {
        let mut a = u32at(rom, 0x0801_9B78 + 4 * i);
        let mut v = Vec::new();
        if a >= 0x0800_0000 {
            loop {
                let dx = rom.u8(a) as i8;
                if dx == 0x7F {
                    break;
                }
                v.push(format!("PanelOffset {{ dx: {dx}, dy: {} }}", rom.u8(a + 1) as i8));
                a += 2;
            }
        }
        writeln!(out, "    &[{}], // {i}", v.join(", ")).unwrap();
    }
    writeln!(out, "];").unwrap();
    let f: Vec<String> = (0..9)
        .map(|i| {
            format!(
                "PanelCondition {{ require: {:#x}, forbid: {:#x} }}",
                u32at(rom, 0x0801_9C34 + 8 * i),
                u32at(rom, 0x0801_9C38 + 8 * i)
            )
        })
        .collect();
    writeln!(out, "/// Whole-field regions (region 0x80 + i): every panel meeting the condition.").unwrap();
    writeln!(out, "pub static FIELD_REGIONS: [PanelCondition; 9] = [{}];", f.join(", ")).unwrap();
    // The game indexes a 28-byte table as receiver * 5 + hitter, so hitter
    // element 5 reads the next receiver's first entry. Materialize that.
    let w = rom.bytes(iwram(0x0300_7444), 28);
    let rows: Vec<String> = (0..6)
        .map(|r| {
            let row: Vec<String> = (0..6).map(|h| w.get(r * 5 + h).copied().unwrap_or(0).to_string()).collect();
            format!("[{}]", row.join(", "))
        })
        .collect();
    writeln!(out, "/// Extra damage multiplier by [receiver element][hitter element] (`byte_3007444`, which the game indexes as r*5+h).").unwrap();
    writeln!(out, "pub static ELEMENT_WEAKNESS: [[u8; 6]; 6] = [{}];", rows.join(", ")).unwrap();
    out
}

/// GBA BIOS LZ77 (type 0x10) decompression.
pub(crate) fn lz77(rom: &Rom, src: u32) -> Option<Vec<u8>> {
    let hdr = u32at(rom, src);
    if hdr & 0xFF != 0x10 {
        return None;
    }
    let size = (hdr >> 8) as usize;
    let mut out = Vec::with_capacity(size);
    let mut o = src + 4;
    while out.len() < size {
        let flags = rom.u8(o);
        o += 1;
        for bit in 0..8 {
            if out.len() >= size {
                break;
            }
            if flags & (0x80 >> bit) != 0 {
                let (b1, b2) = (rom.u8(o) as usize, rom.u8(o + 1) as usize);
                o += 2;
                let n = (b1 >> 4) + 3;
                let disp = ((b1 & 0xF) << 8 | b2) + 1;
                for _ in 0..n {
                    let v = *out.get(out.len().checked_sub(disp)?)?;
                    out.push(v);
                }
            } else {
                out.push(rom.u8(o));
                o += 1;
            }
        }
    }
    Some(out)
}

/// Animation timing of every battle sprite: per animation, its frames'
/// (duration, flags). Sprites are (category byte offset, index) into
/// `SpritePointersList`.
fn sprites(rom: &Rom) -> String {
    const LIST: u32 = 0x0803_1CC4;
    const BATTLE_CATEGORIES: u32 = 6;
    let cats: Vec<u32> = (0..10).map(|i| u32at(rom, LIST + 4 * i)).collect();
    let mut sprites: Vec<(u8, u8, Vec<Vec<(u8, u8)>>)> = Vec::new();
    for (ci, &c) in cats.iter().enumerate().take(BATTLE_CATEGORIES as usize) {
        let next = cats.iter().copied().filter(|&s| s > c).min().unwrap_or(c + 0x400);
        for idx in 0..((next - c) / 4).min(256) {
            let p = u32at(rom, c + 4 * idx);
            let data: Vec<u8> = if p & 0x8000_0000 != 0 {
                match lz77(rom, p & 0x7FFF_FFFF) {
                    Some(d) if d.len() > 4 => d[4..].to_vec(),
                    _ => continue,
                }
            } else if (0x0800_0000..0x0900_0000).contains(&p) {
                let o = (p & 0x01FF_FFFF) as usize;
                rom.0[o..(o + 0x80000).min(rom.0.len())].to_vec()
            } else {
                continue;
            };
            let rd32 = |o: usize| data.get(o..o + 4).map(|b| u32::from_le_bytes(b.try_into().unwrap()));
            let Some(first) = rd32(4) else { continue };
            let count = first / 4;
            if count == 0 || count > 256 {
                continue;
            }
            let mut anims = Vec::new();
            let mut ok = true;
            for a in 0..count as usize {
                let Some(off) = rd32(4 + 4 * a) else {
                    ok = false;
                    break;
                };
                let mut f = 4 + off as usize;
                let mut frames = Vec::new();
                loop {
                    let (Some(&dur), Some(&flags)) = (data.get(f + 0x10), data.get(f + 0x12)) else {
                        ok = false;
                        break;
                    };
                    frames.push((dur, flags));
                    if flags & 0x80 != 0 || frames.len() > 512 {
                        break;
                    }
                    f += 0x14;
                }
                if !ok {
                    break;
                }
                anims.push(frames);
            }
            if ok {
                sprites.push(((ci * 4) as u8, idx as u8, anims));
            }
        }
    }
    let mut out = String::from(HEADER);
    writeln!(out, "use super::{{AnimFrame, SpriteAnimations, SpriteId}};\n").unwrap();
    writeln!(out, "const fn f(duration: u8, flags: u8) -> AnimFrame {{\n    AnimFrame {{ duration, flags }}\n}}\n").unwrap();
    writeln!(out, "/// Battle sprites with animation data, sorted by id.").unwrap();
    writeln!(out, "pub static SPRITES: [SpriteAnimations; {}] = [", sprites.len()).unwrap();
    let mut total = (0, 0);
    for (cat, idx, anims) in &sprites {
        let anims: Vec<String> = anims
            .iter()
            .map(|a| {
                let frames: Vec<String> = a.iter().map(|&(d, f)| format!("f({d}, {f:#04x})")).collect();
                format!("&[{}]", frames.join(", "))
            })
            .collect();
        total.0 += anims.len();
        total.1 += sprites_frames(&anims);
        writeln!(
            out,
            "    SpriteAnimations {{ id: SpriteId {{ category: {cat:#04x}, index: {idx:#04x} }}, animations: &[{}] }},",
            anims.join(", ")
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    eprintln!("sprites: {} sprites, {} animations", sprites.len(), total.0);
    out
}

fn sprites_frames(anims: &[String]) -> usize {
    anims.iter().map(|a| a.matches("f(").count()).sum()
}

/// Effect sprite tables: generic effects (`byte_80E0398`, effect object
/// #0) and hit sparks (`off_80E0804`, effect object #4). Each row is sprite
/// category, index, animation, palette.
fn effects(rom: &Rom) -> String {
    let mut out = String::from(HEADER);
    writeln!(out, "use super::{{EffectSprite, SpriteId}};\n").unwrap();
    let table = |out: &mut String, name: &str, doc: &str, base: u32, n: u32| {
        writeln!(out, "/// {doc}").unwrap();
        writeln!(out, "pub static {name}: [EffectSprite; {n}] = [").unwrap();
        for i in 0..n {
            let b = rom.bytes(base + 4 * i, 4);
            writeln!(
                out,
                "    EffectSprite {{ sprite: SpriteId {{ category: {:#04x}, index: {:#04x} }}, anim: {:#04x}, palette: {:#04x} }}, // {i:#04x}",
                b[0], b[1], b[2], b[3]
            )
            .unwrap();
        }
        writeln!(out, "];").unwrap();
    };
    table(&mut out, "EFFECTS", "Generic effects by effect id.", 0x080E_0398, 0x6C);
    table(&mut out, "SPARKS", "Hit sparks by hit-effect id.", 0x080E_0804, 16);
    out
}

/// Player-navi tables: sprites, elements, weapon routines, charge
/// thresholds, status effects, attach points and movement vectors. The
/// row types live in bn6-battle's `data::player`.
fn player(rom: &Rom) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use super::player::{AttachPoint, FormWeapons, NaviRecord, SecondaryElements, SlideVector, StatusEffect, StatusTimer};\n");
    out.push_str("use super::{Element, SpriteId};\n");
    out.push_str("use crate::actor::ActorType;\n\n");
    let list = |items: Vec<String>| items.join(", ");
    let bytes = |a: u32, n: u32| -> String { list((0..n).map(|i| format!("{:#04x}", rom.u8(a + i))).collect()) };
    let sprite = |cat: u8, idx: u8| format!("SpriteId {{ category: {cat:#04x}, index: {idx:#04x} }}");
    let vectors = |a: u32, stride: u32, n: u32| -> String {
        list((0..n)
            .map(|i| {
                let e = a + stride * i;
                format!("SlideVector {{ dx: {}, dy: {}, tiles: {} }}", rom.u8(e) as i8, rom.u8(e + 1) as i8, rom.u8(e + 2))
            })
            .collect())
    };
    const ELEMENTS: [&str; 5] = ["Null", "Fire", "Aqua", "Elec", "Wood"];

    writeln!(out, "/// MegaMan's battle sprite by form (category 0, `byte_800FCBC`).").unwrap();
    let s: Vec<String> = (0..25).map(|i| sprite(0, rom.u8(0x0800_FCBC + i))).collect();
    writeln!(out, "pub static FORM_SPRITES: [SpriteId; 25] = [{}];", list(s)).unwrap();
    writeln!(out, "/// Other navis' battle sprite by navi (category 8, `byte_800FCD5`).").unwrap();
    let s: Vec<String> = (0..12).map(|i| sprite(8, rom.u8(0x0800_FCD5 + i))).collect();
    writeln!(out, "pub static NAVI_SPRITES: [SpriteId; 12] = [{}];", list(s)).unwrap();
    writeln!(out, "/// Element by form (MegaMan) or by navi (`byte_80108B8`).").unwrap();
    let e: Vec<String> = (0..25).map(|i| format!("Element::{}", ELEMENTS[rom.u8(0x0801_08B8 + i) as usize])).collect();
    writeln!(out, "pub static ELEMENTS: [Element; 25] = [{}];", list(e)).unwrap();
    writeln!(out, "/// Secondary-element weakness by form (MegaMan) or by navi (`byte_80108D1`).").unwrap();
    let w: Vec<String> = (0..25).map(|i| format!("SecondaryElements({:#04x})", rom.u8(0x0801_08D1 + i))).collect();
    writeln!(out, "pub static WEAKNESSES: [SecondaryElements; 25] = [{}];", list(w)).unwrap();
    writeln!(out, "/// Weapon routines by form (`byte_8020354`).").unwrap();
    let f: Vec<String> = (0..25)
        .map(|i| {
            let b = rom.bytes(0x0802_0354 + 6 * i, 6);
            format!(
                "FormWeapons {{ mode9_a: {:#04x}, a_charge: {:#04x}, buster: {:#04x}, charge_shot: {:#04x}, back_special: {:#04x}, alt_a_charge: {:#04x} }}",
                b[0], b[1], b[2], b[3], b[4], b[5]
            )
        })
        .collect();
    writeln!(out, "pub static FORM_WEAPONS: [FormWeapons; 25] = [{}];", list(f)).unwrap();
    let rows: Vec<String> =
        (0..50).map(|r| format!("[{}]", list((0..5).map(|c| rom.u16(0x0802_0404 + 10 * r + 2 * c).to_string()).collect()))).collect();
    writeln!(out, "/// Ticks to a full charge by charge routine and Charge stat (`byte_8020404`).").unwrap();
    writeln!(out, "pub static CHARGE_THRESHOLDS: [[u16; 5]; 50] = [{}];", list(rows)).unwrap();
    let rows: Vec<String> = (0..5).map(|n| format!("[{}]", list((0..6).map(|k| rom.u8(0x0802_09CC + 6 * n + k).to_string()).collect()))).collect();
    let steps: Vec<String> = (0..10).map(|i| format!("{:#06x}", u32at(rom, 0x0801_0B2C + 4 * i))).collect();
    writeln!(out, "/// The deletion times (BCD minutes:seconds.hundredths) that step an SP navi chip's damage down (`byte_8010B2C`).").unwrap();
    writeln!(out, "pub static SP_TIME_STEPS: [u32; 10] = [{}];", list(steps)).unwrap();
    let sp_rows: Vec<String> = (0..18)
        .map(|n| format!("[{}]", list((0..11).map(|k| rom.u16(0x0802_0E54 + 0x16 * n + 2 * k).to_string()).collect())))
        .collect();
    writeln!(out, "/// SP navi chip damage by navi chip and deletion-time step (`byte_8020E54`).").unwrap();
    writeln!(out, "pub static SP_CHIP_DAMAGE: [[u16; 11]; 18] = [{}];", list(sp_rows)).unwrap();
    writeln!(out, "/// Ticks of recovery after a buster shot, by Rapid stat and open panels ahead (`byte_80209CC`).").unwrap();
    writeln!(out, "pub static BUSTER_RECOVERY: [[u8; 6]; 5] = [{}];", list(rows)).unwrap();
    let rows: Vec<String> = (0..23).map(|n| format!("[{}]", bytes(0x0802_0FE0 + 11 * n, 11))).collect();
    writeln!(out, "/// Move end lag by navi and navi variant (`byte_8020FE0`).").unwrap();
    writeln!(out, "pub static MOVE_LAG: [[u8; 11]; 23] = [{}];", list(rows)).unwrap();
    // Status effects: per group a pointer to 8-byte entries {u32 F2 bits,
    // u16 duration, u8 CollisionData offset}. Nibbles past a group's end
    // read the following bytes, as in the game.
    let timer = |off: u8| -> String {
        match off {
            0x1C => "StatusTimer::Paralyze".into(),
            0x1E => "StatusTimer::Confuse".into(),
            0x20 => "StatusTimer::Blind".into(),
            0x22 => "StatusTimer::Immobilize".into(),
            0x24 => "StatusTimer::Flash".into(),
            0x26 => "StatusTimer::SemiIntangible".into(),
            0x28 => "StatusTimer::Invulnerable".into(),
            0x2A => "StatusTimer::Freeze".into(),
            0x2C => "StatusTimer::Bubble".into(),
            0x0A => "StatusTimer::CollisionPanel".into(),
            o => format!("StatusTimer::Other({o:#04x})"),
        }
    };
    let groups: Vec<String> = (0..6)
        .map(|g| {
            let p = u32at(rom, 0x0802_09EC + 4 * g);
            let e: Vec<String> = (0..16)
                .map(|n| {
                    let a = p + 8 * n;
                    format!("StatusEffect {{ requests: {:#x}, duration: {}, timer: {} }}", u32at(rom, a), rom.u16(a + 4), timer(rom.u8(a + 6)))
                })
                .collect();
            format!("[{}]", list(e))
        })
        .collect();
    writeln!(out, "/// Status effects by (status >> 4) - 1 and status & 0xF (`off_80209EC`).").unwrap();
    writeln!(out, "pub static STATUS_EFFECTS: [[StatusEffect; 16]; 6] = [{}];", list(groups)).unwrap();
    // Per player NameID (0x1A0..=0x1C3): the actor record and the sprite
    // attach points (`sub_8018810`: enemy struct sprite -> attach table).
    const ACTOR_TYPES: [&str; 3] = ["Virus", "Navi", "Player"];
    let mut records = Vec::new();
    let mut attach = Vec::new();
    for name in 0x1A0..=0x1C3u32 {
        let rec = rom.bytes(0x0801_82C4 + 3 * name, 3);
        records.push(format!(
            "NaviRecord {{ version: {}, actor_type: ActorType::{}, ai_index: {} }}",
            rec[0], ACTOR_TYPES[rec[1] as usize], rec[2]
        ));
        let st = u32at(rom, u32at(rom, 0x0800_F230 + 4 * rec[1] as u32) + 4 * rec[2] as u32);
        let (cat, mut idx) = (rom.u8(st) as u32, rom.u8(st + 1) as u32);
        if cat == 0 {
            idx = rom.u8(0x0801_88B0 + idx) as u32;
        }
        let table = u32at(rom, 0x0801_88A0 + cat) + 0x44 * idx;
        let points: Vec<String> = (0..34)
            .map(|i| format!("AttachPoint {{ x: {}, y: {} }}", rom.u8(table + 2 * i) as i8, rom.u8(table + 2 * i + 1) as i8))
            .collect();
        attach.push(format!("[{}]", list(points)));
    }
    writeln!(out, "/// Actor records by NameID - 0x1A0 (`byte_80182C4`).").unwrap();
    writeln!(out, "pub static NAVI_RECORDS: [NaviRecord; 36] = [{}];", list(records)).unwrap();
    writeln!(out, "/// Sprite attach points by NameID - 0x1A0 (`sub_8018810`).").unwrap();
    writeln!(out, "pub static NAVI_ATTACH_POINTS: [[AttachPoint; 34]; 36] = [{}];", list(attach)).unwrap();
    writeln!(out, "/// Push vectors by hit-modifier bit (+5 with 0x80) (`byte_800E58C`).").unwrap();
    writeln!(out, "pub static PUSH_VECTORS: [SlideVector; 10] = [{}];", vectors(0x0800_E58C, 3, 10)).unwrap();
    writeln!(out, "/// Ice slide vectors by collision direction (`byte_800E4E8`).").unwrap();
    writeln!(out, "pub static ICE_VECTORS: [SlideVector; 6] = [{}];", vectors(0x0800_E4E8, 4, 6)).unwrap();
    writeln!(out, "/// Road slide vectors by panel type - 9 (`byte_800E538`).").unwrap();
    writeln!(out, "pub static ROAD_VECTORS: [SlideVector; 4] = [{}];", vectors(0x0800_E538, 4, 4)).unwrap();
    let bob: Vec<String> = rom.bytes(0x0801_7868, 32).iter().map(|&b| (b as i8).to_string()).collect();
    writeln!(out, "/// Bubble bobbing height by timer (`byte_8017868`).").unwrap();
    writeln!(out, "pub static BUBBLE_BOB: [i8; 32] = [{}];", list(bob)).unwrap();
    writeln!(out, "/// Buster damage bonus by navi (`byte_80126A4`).").unwrap();
    writeln!(out, "pub static BUSTER_BONUS_BY_NAVI: [u8; 12] = [{}];", bytes(0x0801_26A4, 12)).unwrap();
    writeln!(out, "/// Buster damage bonus by form (`off_80126B0`).").unwrap();
    writeln!(out, "pub static BUSTER_BONUS_BY_FORM: [u8; 25] = [{}];", bytes(0x0801_26B0, 25)).unwrap();
    writeln!(out, "/// HP-bug drain period by bug level (`byte_80102A4`).").unwrap();
    writeln!(out, "pub static HP_BUG_PERIODS: [u8; 8] = [{}];", bytes(0x0801_02A4, 8)).unwrap();
    out
}

/// Battle actor lists: every list referenced by `BattleSettingsList1`
/// (192 16-byte settings records; bytes 12..16 point at the list). A list
/// is 4-byte entries up to one whose byte 0 has high nibble 0xF; the
/// spawn loop (`sub_8007368`) reads kind = b0 >> 4, side = b0 & 1,
/// x = b1 & 7, y = b1 >> 4, and kind-specific bytes b2, b3.
fn actor_lists(rom: &Rom) -> String {
    const SETTINGS: u32 = 0x080B_0D88;
    const COUNT: u32 = 192;
    let mut sources: Vec<u32> = (0..COUNT).map(|i| u32at(rom, SETTINGS + 16 * i + 12)).collect();
    sources.sort_unstable();
    sources.dedup();
    let mut out = String::from(HEADER);
    out.push_str("use crate::setup::{ActorEntry, ActorKind, ActorList};\n\n");
    writeln!(out, "/// Every actor list the battle settings table refers to, by ROM address.").unwrap();
    writeln!(out, "pub static ACTOR_LISTS: [ActorList; {}] = [", sources.len()).unwrap();
    for &source in &sources {
        let mut entries = Vec::new();
        let mut a = source;
        loop {
            let b = rom.bytes(a, 4);
            if b[0] >> 4 == 0xF {
                break;
            }
            // Each kind's spawn routine reads only some of the bytes;
            // the rest must be clear so the decoded entry says it all.
            let side = b[0] & 1;
            let unused = |mask0: u8, used2: bool| {
                assert!(
                    b[0] & mask0 == 0 && b[1] & 0x08 == 0 && (used2 || b[2] == 0) && b[3] == 0,
                    "actor entry {a:#010x} sets bytes its spawn routine ignores: {b:02x?}"
                )
            };
            let kind = match b[0] >> 4 {
                0 => {
                    unused(0x0E, false);
                    "ActorKind::Navi".to_string()
                }
                3 => {
                    unused(0x0F, false);
                    "ActorKind::Object6E".to_string()
                }
                8 => {
                    unused(0x0F, true);
                    format!("ActorKind::Rock {{ variant: {} }}", b[2])
                }
                9 => {
                    unused(0x0F, true);
                    format!("ActorKind::Object7D {{ variant: {} }}", b[2])
                }
                k => panic!("actor entry {a:#010x}: kind {k} has no ActorKind yet"),
            };
            entries.push(format!("ActorEntry {{ kind: {kind}, alliance: {side}, x: {}, y: {} }}", b[1] & 7, b[1] >> 4));
            a += 4;
        }
        writeln!(out, "    ActorList {{ source: {source:#010x}, entries: &[{}] }},", entries.join(", ")).unwrap();
    }
    out.push_str("];\n");
    out
}

/// The battle settings table (`BattleSettingsList1`, 192 16-byte records)
/// that a set's later rounds are drawn from (`battleSettings_802D2B2`).
/// Byte 1 (read outside the battle simulation) and byte 7 (no reader) are
/// not kept, as in `BattleSettings::netbattle_from_bytes`.
fn battle_settings(rom: &Rom) -> String {
    const SETTINGS: u32 = 0x080B_0D88;
    const COUNT: u32 = 192;
    let mut sources: Vec<u32> = (0..COUNT).map(|i| u32at(rom, SETTINGS + 16 * i + 12)).collect();
    sources.sort_unstable();
    sources.dedup();
    let mut out = String::from(HEADER);
    out.push_str("use super::ACTOR_LISTS;\nuse crate::setup::BattleSettings;\n\n");
    writeln!(out, "/// `BattleSettingsList1`, by index.").unwrap();
    writeln!(out, "pub static BATTLE_SETTINGS: [BattleSettings; {COUNT}] = [").unwrap();
    for i in 0..COUNT {
        let r = rom.bytes(SETTINGS + 16 * i, 16);
        let source = u32at(rom, SETTINGS + 16 * i + 12);
        let list = sources.binary_search(&source).unwrap();
        writeln!(
            out,
            "    BattleSettings {{ layout: {:#04x}, music: {:#04x}, mode: {}, background: {}, battle_number: {}, panel_pattern: {:#04x}, effects: {:#x}, actors: &ACTOR_LISTS[{list}] }}, // {i:#04x}",
            r[0],
            r[2],
            r[3],
            r[4],
            r[5],
            r[6],
            u32at(rom, SETTINGS + 16 * i + 8),
        )
        .unwrap();
    }
    out.push_str("];\n");
    out
}

/// Cross tables: the body overlays a navi wears (actor object #0x56:
/// sprites `byte_80C4320` and per-animation depth tables `off_80C42D4`)
/// and the extra height of a Cross navi's image as it merges with
/// MegaMan (`byte_80BC758`). The row types live in bn6-battle's
/// `data::cross`.
fn crosses(rom: &Rom) -> String {
    const OVERLAY_SPRITES: u32 = 0x080C_4320;
    const OVERLAY_DEPTHS: u32 = 0x080C_42D4;
    const OVERLAYS: u32 = 19;
    const MERGE_HEIGHTS: u32 = 0x080B_C758;
    const NAVIS: u32 = 13;
    let mut out = String::from(HEADER);
    out.push_str("use super::SpriteId;\nuse super::cross::BodyOverlay;\n\n");
    // The depth tables sit back to back and end where the pointer table
    // starts; an animation past a table's end reads the next one, so each
    // row runs to the end of the block.
    writeln!(out, "/// Body overlays by variant (Param1 of actor object #0x56).").unwrap();
    writeln!(out, "pub static BODY_OVERLAYS: [BodyOverlay; {OVERLAYS}] = [").unwrap();
    for i in 0..OVERLAYS {
        let s = rom.bytes(OVERLAY_SPRITES + 2 * i, 2);
        let depths = u32at(rom, OVERLAY_DEPTHS + 4 * i);
        assert!(depths < OVERLAY_DEPTHS, "overlay depth table {depths:#x} outside the block");
        let front: Vec<&str> = rom
            .bytes(depths, (OVERLAY_DEPTHS - depths) as usize)
            .iter()
            .map(|&b| match b {
                0 => "false",
                1 => "true",
                v => panic!("overlay depth byte {v:#x}"),
            })
            .collect();
        writeln!(
            out,
            "    BodyOverlay {{ sprite: SpriteId {{ category: {:#04x}, index: {:#04x} }}, in_front: &[{}] }}, // {i:#04x}",
            s[0],
            s[1],
            front.join(", ")
        )
        .unwrap();
    }
    out.push_str("];\n");
    let heights: Vec<String> = (0..NAVIS)
        .map(|i| {
            let v = u32at(rom, MERGE_HEIGHTS + 4 * i) as i32;
            assert_eq!(v & 0xFFFF, 0, "merge height {v:#x} is not whole pixels");
            (v >> 16).to_string()
        })
        .collect();
    writeln!(out, "/// Extra height (whole pixels) of a navi's image merging with MegaMan, by navi.").unwrap();
    writeln!(out, "pub static MERGE_HEIGHTS: [i16; {NAVIS}] = [{}];", heights.join(", ")).unwrap();
    out
}

/// Field-object tables: the rock variants (`byte_80CF934`, 8-byte rows
/// selected by the rock's first parameter) and the sprite of each kind of
/// obstacle when it is absorbed (`byte_80E98C0`).
fn obstacles(rom: &Rom) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use super::{Element, RockKind, SpriteId};\n\n");
    const ROCKS: u32 = 0x080C_F934;
    let rows: Vec<String> = (0..4)
        .map(|i| {
            // Row bytes: standing animation, (unused), HP / 2, debris
            // palette, break sound (u16), name id (u16). The rock's init
            // (`sub_80CF974`) turns HP / 2 = 0 into 1 HP and makes
            // variants 3 and up aqua.
            let r = ROCKS + 8 * i;
            let hp = match rom.u8(r + 2) as u16 * 2 {
                0 => 1,
                hp => hp,
            };
            let element = if i >= 3 { "Aqua" } else { "Null" };
            format!(
                "RockKind {{ anim: {}, hp: {hp}, element: Element::{element}, debris_palette: {}, \
                 break_sound: {:#06x}, name_id: {:#06x} }}",
                rom.u8(r),
                rom.u8(r + 3),
                rom.u16(r + 4),
                rom.u16(r + 6)
            )
        })
        .collect();
    writeln!(out, "/// Rocks by variant, the rock's first parameter (`byte_80CF934`).").unwrap();
    writeln!(out, "pub static ROCKS: [RockKind; 4] = [\n    {},\n];", rows.join(",\n    ")).unwrap();
    const ABSORBED: u32 = 0x080E_98C0;
    let sprites: Vec<String> = (0..15)
        .map(|i| {
            let (category, index) = (rom.u8(ABSORBED + 2 * i), rom.u8(ABSORBED + 2 * i + 1));
            format!("SpriteId {{ category: {category:#04x}, index: {index:#04x} }}")
        })
        .collect();
    writeln!(out, "/// The sprite an absorbed obstacle flies with, by obstacle kind (`byte_80E98C0`).").unwrap();
    writeln!(out, "pub static ABSORBED_SPRITES: [SpriteId; 15] = [\n    {},\n];", sprites.join(",\n    ")).unwrap();
    out
}

/// Chip-attack tables: the secondary elements chip families add, the
/// attachment sprites (`byte_80B8BD4`, attachment object #5) and the
/// GunDelSol tables (`dword_80EDBC8`, `byte_80EDBB8`, and the sun beam's
/// sprites at `dword_80E5C28`).
fn attacks(rom: &Rom) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use super::SpriteId;\n");
    out.push_str("use super::attacks::{AttachmentKind, SunBeamLook};\n");
    out.push_str("use super::player::SecondaryElements;\n\n");
    let list = |items: Vec<String>| items.join(", ");
    let sprite = |cat: u8, idx: u8| format!("SpriteId {{ category: {cat:#04x}, index: {idx:#04x} }}");

    let families: Vec<String> = (0..16).map(|i| format!("SecondaryElements({:#04x})", rom.u8(0x0801_29E4 + i))).collect();
    writeln!(out, "/// The secondary elements a chip family adds to its attacks (`byte_80129E4`).").unwrap();
    writeln!(out, "pub static FAMILY_ELEMENTS: [SecondaryElements; 16] = [{}];", list(families)).unwrap();

    // Five-byte rows: sprite category and index, palette, lift, attach
    // point (0 = not attached to a point).
    const ATTACHMENTS: u32 = 0x080B_8BD4;
    let rows: Vec<String> = (0..52)
        .map(|i| {
            let b = rom.bytes(ATTACHMENTS + 5 * i, 5);
            let point = if b[4] == 0 { "None".to_string() } else { format!("Some({})", b[4]) };
            format!(
                "AttachmentKind {{ sprite: {}, palette: {}, lift: {}, attach_point: {point} }}",
                sprite(b[0], b[1]),
                b[2],
                b[3] as i8
            )
        })
        .collect();
    writeln!(out, "/// Attachment kinds, the attachment's first parameter (`byte_80B8BD4`).").unwrap();
    writeln!(out, "pub static ATTACHMENTS: [AttachmentKind; 52] = [\n    {},\n];", rows.join(",\n    ")).unwrap();

    writeln!(out, "/// GunDelSol's firing ticks by level (`dword_80EDBC8`).").unwrap();
    writeln!(out, "pub static GUN_DEL_SOL_FIRING_TICKS: [u8; 4] = [{}];", list((0..4).map(|i| rom.u8(0x080E_DBC8 + i).to_string()).collect())).unwrap();
    let beams: Vec<String> = (0..2)
        .map(|sun| {
            let row: Vec<String> = (0..4)
                .map(|level| {
                    let a = 0x080E_DBB8 + 2 * (level + 4 * sun);
                    format!("SunBeamLook {{ sprite: {}, palette: {} }}", rom.u8(a), rom.u8(a + 1))
                })
                .collect();
            format!("[{}]", list(row))
        })
        .collect();
    writeln!(out, "/// GunDelSol's sun beam by [sun][level] (`byte_80EDBB8`).").unwrap();
    writeln!(out, "pub static GUN_DEL_SOL_BEAMS: [[SunBeamLook; 4]; 2] = [{}];", list(beams)).unwrap();
    let sprites: Vec<String> = (0..2).map(|i| sprite(rom.u8(0x080E_5C28 + 2 * i), rom.u8(0x080E_5C29 + 2 * i))).collect();
    writeln!(out, "/// The sun beam's sprites, by `SunBeamLook::sprite` (`dword_80E5C28`).").unwrap();
    writeln!(out, "pub static SUN_BEAM_SPRITES: [SpriteId; 2] = [{}];", list(sprites)).unwrap();
    out
}

/// Beast Out lock-on searches (`ho_8026554`, `jt_8026584`): for the lock-on
/// modes that look for a panel near the target (`sub_80265D0`), the panel
/// offsets tried, whether the middle row is preferred afterwards
/// (`sub_80265FE`), and the column shifts tried when nothing fits
/// (`byte_8026735`).
fn lockon(rom: &Rom) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use super::PanelOffset;\n");
    out.push_str("use super::lockon::LockonSearch;\n\n");
    // A list of signed bytes (or byte pairs) up to 0x7F.
    let list = |mut a: u32, pairs: bool| {
        let mut v = Vec::new();
        while rom.u8(a) != 0x7F {
            if pairs {
                v.push(format!("PanelOffset {{ dx: {}, dy: {} }}", rom.u8(a) as i8, rom.u8(a + 1) as i8));
                a += 2;
            } else {
                v.push((rom.u8(a) as i8).to_string());
                a += 1;
            }
        }
        v
    };
    let shifts = list(u32at(rom, 0x0802_67E8), false);
    writeln!(out, "/// Column shifts toward the user tried when no panel next to the target fits (`byte_8026735`).").unwrap();
    writeln!(out, "pub static COLUMN_SHIFTS: [i8; {}] = [{}];", shifts.len(), shifts.join(", ")).unwrap();
    // (mode, literal-pool slot of its offset list, prefers the middle row)
    const MODES: [(u8, u32, bool); 12] = [
        (0x02, 0x0802_67FC, false),
        (0x03, 0x0802_6800, true),
        (0x04, 0x0802_6804, false),
        (0x05, 0x0802_6808, false),
        (0x06, 0x0802_680C, true),
        (0x07, 0x0802_6810, false),
        (0x08, 0x0802_6814, false),
        (0x09, 0x0802_6818, true),
        (0x0C, 0x0802_6824, false),
        (0x0D, 0x0802_6828, false),
        (0x0F, 0x0802_6830, false),
        (0x10, 0x0802_6834, true),
    ];
    writeln!(out, "/// The searching lock-on modes: panels next to the target, dx toward the user's front.").unwrap();
    writeln!(out, "pub static SEARCHES: [LockonSearch; {}] = [", MODES.len()).unwrap();
    for (mode, pool, middle) in MODES {
        let offsets = list(u32at(rom, pool), true);
        writeln!(
            out,
            "    LockonSearch {{ mode: {mode:#04x}, offsets: &[{}], prefers_middle_row: {middle} }},",
            offsets.join(", ")
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
    out
}

pub(crate) fn load_rom(path: &str) -> Rom {
    let rom = Rom(std::fs::read(path).expect("reading ROM"));
    assert_eq!(&rom.0[0xA0..0xB0], b"MEGAMAN6_FXXBR6E", "expected the US Falzar ROM (MEGAMAN6_FXXBR6E)");
    rom
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.first().map(String::as_str) == Some("assets") {
        assets::main(&args[1..]);
        return;
    }
    if args.first().map(String::as_str) == Some("content") {
        content::main(&args[1..]);
        return;
    }
    if args.first().map(String::as_str) == Some("graphics") {
        let (Some(rom), Some(out)) = (args.get(1), args.get(2)) else {
            eprintln!("usage: bn6-extract graphics <rom> <out-dir>");
            std::process::exit(2);
        };
        graphics::run(&load_rom(rom), std::path::Path::new(out));
        return;
    }
    let Some(rom) = args.first() else {
        eprintln!(
            "usage: bn6-extract <rom> [out-dir] | assets <rom> <sound-bank> | graphics <rom> <out-dir> | content <rom> <pack-dir>"
        );
        std::process::exit(2);
    };
    let rom = load_rom(rom);
    let out_dir = args
        .get(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../bn6-battle/src/data"));
    std::fs::write(out_dir.join("chips_generated.rs"), chips(&rom)).unwrap();
    std::fs::write(out_dir.join("banners_generated.rs"), banners(&rom)).unwrap();
    std::fs::write(out_dir.join("field_generated.rs"), field(&rom)).unwrap();
    std::fs::write(out_dir.join("collision_generated.rs"), collision(&rom)).unwrap();
    std::fs::write(out_dir.join("sprites_generated.rs"), sprites(&rom)).unwrap();
    std::fs::write(out_dir.join("effects_generated.rs"), effects(&rom)).unwrap();
    std::fs::write(out_dir.join("player_generated.rs"), player(&rom)).unwrap();
    std::fs::write(out_dir.join("actor_lists_generated.rs"), actor_lists(&rom)).unwrap();
    std::fs::write(out_dir.join("battle_settings_generated.rs"), battle_settings(&rom)).unwrap();
    std::fs::write(out_dir.join("cross_generated.rs"), crosses(&rom)).unwrap();
    std::fs::write(out_dir.join("obstacles_generated.rs"), obstacles(&rom)).unwrap();
    std::fs::write(out_dir.join("attacks_generated.rs"), attacks(&rom)).unwrap();
    std::fs::write(out_dir.join("lockon_generated.rs"), lockon(&rom)).unwrap();
    eprintln!("wrote {}", out_dir.display());
}
