//! Extract game data from the original ROM into Rust source for bn6-battle.
//!
//! Usage: bn6-extract <exe6f_rom_f_e.srl> [out-dir]
//! (out-dir defaults to crates/bn6-battle/src/data)

use std::fmt::Write as _;
use std::path::PathBuf;

struct Rom(Vec<u8>);

impl Rom {
    fn u8(&self, a: u32) -> u8 {
        self.0[(a & 0x01FF_FFFF) as usize]
    }
    fn u16(&self, a: u32) -> u16 {
        u16::from_le_bytes([self.u8(a), self.u8(a + 1)])
    }
    fn bytes(&self, a: u32, n: usize) -> &[u8] {
        let o = (a & 0x01FF_FFFF) as usize;
        &self.0[o..o + n]
    }
}

const HEADER: &str = "// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.\n\n";

/// The chip data table (ChipDataArr, 0x2C-byte records).
fn chips(rom: &Rom) -> String {
    const TABLE: u32 = 0x0802_1DA8;
    const RECORD: u32 = 0x2C;
    const COUNT: u32 = 411;
    let mut out = String::from(HEADER);
    out.push_str("use super::{ChipCode, ChipData};\n\n");
    writeln!(out, "pub static CHIPS: [ChipData; {COUNT}] = [").unwrap();
    for id in 0..COUNT {
        let r = TABLE + id * RECORD;
        let codes: Vec<String> =
            rom.bytes(r, 4).iter().filter(|&&c| c != 0xFF).map(|c| format!("ChipCode({c})")).collect();
        writeln!(
            out,
            "    // {id:#05x}\n    ChipData {{ codes: &[{}], element: {}, rarity: {}, unk_06: {}, unk_07: {}, mb: {}, unk_09: {:#04x}, unk_0a: {:#04x}, unk_0b: {:#04x}, unk_0c_17: {:?}, unk_18: {:#06x}, damage: {}, unk_1c: {:#06x}, unk_1e: {} }},",
            codes.join(", "),
            rom.u8(r + 4),
            rom.u8(r + 5),
            rom.u8(r + 6),
            rom.u8(r + 7),
            rom.u8(r + 8),
            rom.u8(r + 9),
            rom.u8(r + 0xA),
            rom.u8(r + 0xB),
            rom.bytes(r + 0xC, 12),
            rom.u16(r + 0x18),
            rom.u16(r + 0x1A),
            rom.u16(r + 0x1C),
            rom.u8(r + 0x1E),
        )
        .unwrap();
    }
    out.push_str("];\n");
    out
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let rom = Rom(std::fs::read(&args[0]).expect("reading ROM"));
    assert_eq!(&rom.0[0xA0..0xB0], b"MEGAMAN6_FXXBR6E", "expected US Falzar (exe6f_rom_f_e.srl)");
    let out_dir = args
        .get(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../bn6-battle/src/data"));
    std::fs::write(out_dir.join("chips_generated.rs"), chips(&rom)).unwrap();
    eprintln!("wrote {}", out_dir.display());
}
