//! Extract game data from the original ROM into Rust source for bn6-battle.
//!
//! Usage: bn6-extract <exe6f_rom_f_e.srl> [out-dir]
//! (out-dir defaults to crates/bn6-battle/src/data)

use std::fmt::Write as _;
use std::path::PathBuf;

struct Rom(Vec<u8>);

impl Rom {
    fn u8(&self, a: u32) -> u8 {
        self.0[(a & 0x01FF_FFFF) as usize]
    }
    fn u16(&self, a: u32) -> u16 {
        u16::from_le_bytes([self.u8(a), self.u8(a + 1)])
    }
    fn bytes(&self, a: u32, n: usize) -> &[u8] {
        let o = (a & 0x01FF_FFFF) as usize;
        &self.0[o..o + n]
    }
}

/// The game's text encoding for bytes 0x00-0xDF (from the disassembly's charmap).
const CHARSET: [&str; 0xE0] = [
    "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E",
    "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U",
    "V", "W", "X", "Y", "Z", "*", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j",
    "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
    "[RV]", "[BX]", "[EX]", "[SP]", "[FZ]", "ウ", "ア", "イ", "オ", "エ", "ケ", "コ", "カ", "ク", "キ", "セ",
    "サ", "ソ", "シ", "ス", "テ", "ト", "ツ", "タ", "チ", "ネ", "ノ", "ヌ", "ナ", "ニ", "ヒ", "ヘ",
    "ホ", "ハ", "フ", "ミ", "マ", "メ", "ム", "モ", "ヤ", "ヨ", "ユ", "ロ", "ル", "リ", "レ", "ラ",
    "ン", "熱", "斗", "ワ", "ヲ", "ギ", "ガ", "ゲ", "ゴ", "グ", "ゾ", "ジ", "ゼ", "ズ", "ザ", "デ",
    "ド", "ヅ", "ダ", "ヂ", "ベ", "ビ", "ボ", "バ", "ブ", "ピ", "パ", "ペ", "プ", "ポ", "ゥ", "ァ",
    "ィ", "ォ", "ェ", "ュ", "ヴ", "ッ", "ョ", "ャ", "-", "×", "=", ":", "%", "?", "+", "█",
    "[bat]", "ー", "!", "&", ",", "゜", ".", "・", ";", "'", "\"", "~", "/", "(", ")", "｢",
    "｣", " ", "_", "[z]", "[L]", "[B]", "[R]", "[A]", "あ", "い", "け", "く", "き", "こ", "か", "せ",
    "そ", "す", "さ", "し", "つ", "と", "て", "た", "ち", "ね", "の", "な", "ぬ", "に", "へ", "ふ",
    "ほ", "は", "ひ", "め", "む", "み", "も", "ま", "ゆ", "よ", "や", "る", "ら", "り", "ろ", "れ",
];

/// Decode string `index` of a text archive (u16 offsets, then strings).
fn archive_string(rom: &Rom, archive: u32, index: u32) -> String {
    let mut a = archive + rom.u16(archive + 2 * index) as u32;
    let mut s = String::new();
    loop {
        let b = rom.u8(a) as usize;
        if b >= CHARSET.len() {
            return s;
        }
        s.push_str(CHARSET[b]);
        a += 1;
    }
}

fn chip_name(rom: &Rom, id: u32) -> String {
    const NAMES0: u32 = 0x086E_A94C;
    const NAMES1: u32 = 0x086E_B354;
    if id <= 0xFF { archive_string(rom, NAMES0, id) } else { archive_string(rom, NAMES1, id & 0xFF) }
}

const HEADER: &str = "// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.\n\n";

/// The chip data table (ChipDataArr, 0x2C-byte records).
fn chips(rom: &Rom) -> String {
    const TABLE: u32 = 0x0802_1DA8;
    const RECORD: u32 = 0x2C;
    const COUNT: u32 = 411;
    let mut out = String::from(HEADER);
    out.push_str("use super::{ChipClass, ChipCode, ChipData, ChipFlags, Element};\n\n");
    writeln!(out, "pub static CHIPS: [ChipData; {COUNT}] = [").unwrap();
    for id in 0..COUNT {
        let r = TABLE + id * RECORD;
        let codes: Vec<String> =
            rom.bytes(r, 4).iter().filter(|&&c| c != 0xFF).map(|c| format!("ChipCode({c})")).collect();
        let name = chip_name(rom, id);
        let u32at = |a: u32| u32::from_le_bytes(rom.bytes(a, 4).try_into().unwrap());
        writeln!(
            out,
            "    ChipData {{ name: {name:?}, codes: &[{}], element: Element::{}, rarity: {}, family: {}, class: ChipClass::{}, mb: {}, flags: ChipFlags({:#04x}), hit_param: {}, action: {:#04x}, subtype: {}, unk_0d: {}, unk_0e: {}, beast_lockon: {}, params: {:#010x}, lockout: {}, lib_index: {}, flags2: {:#04x}, lockon_mode: {}, sort_key: {:#06x}, damage: {}, library_no: {}, slotin_max: {}, dark_subst: {} }}, // {id:#05x}",
            codes.join(", "),
            ["Null", "Fire", "Aqua", "Elec", "Wood"][rom.u8(r + 4) as usize],
            rom.u8(r + 5),
            rom.u8(r + 6),
            ["Standard", "Mega", "Giga", "Special", "ProgramAdvance"][rom.u8(r + 7) as usize],
            rom.u8(r + 8),
            rom.u8(r + 9),
            rom.u8(r + 0xA),
            rom.u8(r + 0xB),
            rom.u8(r + 0xC),
            rom.u8(r + 0xD),
            rom.u8(r + 0xE),
            rom.u8(r + 0xF),
            u32at(r + 0x10),
            rom.u8(r + 0x14),
            rom.u8(r + 0x15),
            rom.u8(r + 0x16),
            rom.u8(r + 0x17),
            rom.u16(r + 0x18),
            rom.u16(r + 0x1A),
            rom.u16(r + 0x1C),
            rom.u8(r + 0x1E),
            rom.u8(r + 0x1F),
        )
        .unwrap();
    }
    out.push_str("];\n");
    out
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let rom = Rom(std::fs::read(&args[0]).expect("reading ROM"));
    assert_eq!(&rom.0[0xA0..0xB0], b"MEGAMAN6_FXXBR6E", "expected US Falzar (exe6f_rom_f_e.srl)");
    let out_dir = args
        .get(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../bn6-battle/src/data"));
    std::fs::write(out_dir.join("chips_generated.rs"), chips(&rom)).unwrap();
    eprintln!("wrote {}", out_dir.display());
}
