//! Content-layer tests: the content packs' data agree with the engine's
//! generated tables, and every content runtime plays the GunDelSol
//! scenario tick for tick like the built-in kinds.

use crate::data::attacks;

/// The Luau data module the pack's `data/attacks.luau` must hold, rendered
/// from the engine's tables (which bn6-extract generates).
fn luau_attack_data() -> String {
    let mut s = String::from(
        "--!strict\n\
         -- Attack data for the slice, rendered from crates/bn6-battle/src/data/attacks_generated.rs\n\
         -- (itself generated by bn6-extract) by the bn6-battle test `luau_data_matches_the_engine`.\n\
         -- Do not edit; rerun that test with BN6_WRITE_CONTENT_DATA=1. Tables are keyed by the\n\
         -- game's 0-based indices.\n\n\
         -- (Its row types are declared for the pack in types.d.luau.)\n\n\
         local function attachment(category: number, index: number, palette: number, lift: number, attach_point: number?): AttachmentKind\n    \
         return { sprite = { category = category, index = index }, palette = palette, lift = lift, attach_point = attach_point }\nend\n\n\
         return {\n    -- Attachment kinds, the attachment's first parameter (`byte_80B8BD4`).\n    ATTACHMENTS = {\n",
    );
    for kind in 0..52u8 {
        let k = attacks::attachment(kind);
        let point = k.attach_point.map_or("nil".to_string(), |p| p.to_string());
        s += &format!(
            "        [{kind:#04x}] = attachment({:#04x}, {:#04x}, {}, {}, {point}),\n",
            k.sprite.category, k.sprite.index, k.palette, k.lift
        );
    }
    s += "    } :: { [number]: AttachmentKind },\n\n";
    s += "    -- GunDelSol's firing ticks by level (`dword_80EDBC8`).\n    GUN_DEL_SOL_FIRING_TICKS = { [0] = ";
    s += &(0..4).map(|l| attacks::gun_del_sol_firing_ticks(l).to_string()).collect::<Vec<_>>().join(", ");
    s += " },\n\n    -- GunDelSol's sun beam by [sun][level], sun = 0 or 1 (`byte_80EDBB8`).\n    GUN_DEL_SOL_BEAMS = {\n";
    for sun in [false, true] {
        let looks: Vec<String> = (0..4)
            .map(|l| {
                let b = attacks::gun_del_sol_beam(sun, l);
                format!("{{ sprite = {}, palette = {} }}", b.sprite, b.palette)
            })
            .collect();
        s += &format!("        [{}] = {{ [0] = {} }},\n", sun as u8, looks.join(", "));
    }
    s += "    } :: { [number]: { [number]: SunBeamLook } },\n\n";
    s += "    -- The sun beam's sprites, by `SunBeamLook.sprite` (`dword_80E5C28`).\n    SUN_BEAM_SPRITES = { [0] = ";
    s += &(0..2)
        .map(|i| {
            let id = attacks::sun_beam_sprite(i);
            format!("{{ category = {:#04x}, index = {:#04x} }}", id.category, id.index)
        })
        .collect::<Vec<_>>()
        .join(", ");
    s += " } :: { [number]: SpriteId },\n}\n";
    s
}

#[test]
fn luau_data_matches_the_engine() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../content/bn6/data/attacks.luau");
    let want = luau_attack_data();
    if std::env::var_os("BN6_WRITE_CONTENT_DATA").is_some() {
        std::fs::write(path, &want).unwrap();
    }
    let have = std::fs::read_to_string(path).unwrap_or_default();
    assert!(have == want, "content/bn6/data/attacks.luau is stale: rerun with BN6_WRITE_CONTENT_DATA=1");
}

#[cfg(feature = "rust-content")]
#[test]
fn rust_content_data_matches_the_engine() {
    use bn6_content_rust::data as rc;
    for kind in 0..52u8 {
        let (a, b) = (attacks::attachment(kind), rc::ATTACHMENTS[kind as usize]);
        assert_eq!((a.sprite, a.palette, a.lift, a.attach_point), (b.sprite, b.palette, b.lift, b.attach_point));
    }
    for level in 0..4u8 {
        assert_eq!(attacks::gun_del_sol_firing_ticks(level), rc::GUN_DEL_SOL_FIRING_TICKS[level as usize]);
        for sun in [false, true] {
            let (a, b) = (attacks::gun_del_sol_beam(sun, level), rc::GUN_DEL_SOL_BEAMS[sun as usize][level as usize]);
            assert_eq!((a.sprite, a.palette), (b.sprite, b.palette));
        }
    }
    for i in 0..2u8 {
        assert_eq!(attacks::sun_beam_sprite(i), rc::SUN_BEAM_SPRITES[i as usize]);
    }
}

// ---- Every runtime plays the same battle -------------------------------------------

use crate::battle::Battle;
use crate::content::Content;
use crate::scenario;

/// The digest of what every runtime represents the same way: everything
/// but the kinds' and actions' own state structs (`Vars`, `ActionVars`),
/// whose representation differs between the built-in kinds and content.
/// What those kinds do to shared state is all still in.
fn engine_digest(b: &Battle) -> u64 {
    use crate::object::{ObjectRef, Pool, SLOTS};
    let mut b = b.clone();
    for pool in Pool::ALL {
        for slot in 0..SLOTS as u8 {
            b.objects.get_mut(ObjectRef { pool, slot }).vars = crate::kinds::Vars::None;
        }
    }
    for i in 0..crate::actor::SLOTS as u8 {
        b.actors.get_mut(crate::actor::ActorId(i)).attack.action = Default::default();
    }
    b.digest()
}

/// Each tick's digest of what every runtime represents the same way,
/// with the sound cues it made.
fn engine_digests(tape: &[scenario::Tick], mut b: Battle) -> Vec<(u64, Vec<crate::sound::SoundCue>)> {
    tape.iter()
        .map(|t| {
            b.tick(&t.input, t.events.clone());
            (engine_digest(&b), b.sound_cues().to_vec())
        })
        .collect()
}

#[test]
fn every_runtime_plays_the_duel_like_the_engine() {
    let tape = scenario::record(900);
    let want = engine_digests(&tape, Battle::with_content(scenario::setup(), Content::builtin()));
    #[allow(unused_mut)]
    let mut runs: Vec<(&str, Content)> = Vec::new();
    #[cfg(feature = "rust-content")]
    runs.push(("rust", Content::rust()));
    #[cfg(feature = "luau")]
    runs.push(("luau", Content::luau().unwrap()));
    #[cfg(feature = "luau-jit")]
    runs.push((
        "luau native",
        Content::luau_with(bn6_luau::Options { native_code: true, ..Default::default() }).unwrap(),
    ));
    for (name, content) in runs {
        let have = engine_digests(&tape, Battle::with_content(scenario::setup(), content));
        let first = have.iter().zip(&want).position(|(a, b)| a != b);
        assert_eq!(first, None, "{name} content diverges from the engine's kinds at tick {first:?}");
    }
}

// ---- Luau keeps no state ----------------------------------------------------------------

#[cfg(feature = "luau")]
mod luau {
    use super::*;
    use crate::battle::TickEvents;
    use crate::content::luau_pack;

    /// Each tick's state digest over a tape.
    fn digests(tape: &[scenario::Tick], mut b: Battle) -> Vec<u64> {
        tape.iter()
            .map(|t| {
                b.tick(&t.input, t.events.clone());
                b.digest()
            })
            .collect()
    }

    #[test]
    fn luau_is_the_default_content_with_the_feature() {
        assert_eq!(Battle::new(scenario::setup()).content.runtime(), "luau");
    }

    /// The pack with text replaced in one module (each `(from, to)` once).
    fn patched(module: &str, edits: &[(&str, &str)]) -> bn6_luau::Pack {
        bn6_luau::Pack::new(luau_pack().modules().map(|(path, src)| {
            let mut src = src.to_string();
            if path == module {
                for (from, to) in edits {
                    assert!(src.contains(from), "{module}.luau has no {from:?}");
                    src = src.replacen(from, to, 1);
                }
            }
            (path.to_string(), src)
        }))
    }

    fn load(pack: &bn6_luau::Pack) -> Result<Content, String> {
        bn6_luau::LuauContent::load(pack, bn6_luau::Options::default())
            .and_then(Content::new)
            .map_err(|e| e.to_string())
    }

    /// Play the duel with `content`: the content error it stopped on, if
    /// any.
    fn play_error(content: Content) -> Option<String> {
        let tape = scenario::record(500);
        let r = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| scenario::play(&tape, content)));
        r.err().map(|e| e.downcast_ref::<String>().cloned().unwrap_or_default())
    }

    const UPDATE: &str = "function gun_del_sol.update(me: Object, s: State)\n";

    /// GunDelSol's update with `line` added at its top.
    fn in_update(line: &str) -> bn6_luau::Pack {
        patched("chips/gun_del_sol", &[(UPDATE, &format!("{UPDATE}    {line}\n"))])
    }

    #[test]
    fn state_in_module_locals_is_rejected_at_load() {
        let pack = patched(
            "objects/sun_beam",
            &[
                ("local sun_beam = {", "local hums = 0\nlocal sun_beam = {"),
                ("    s.ticks += 1\n", "    s.ticks += 1\n    hums += 1\n"),
            ],
        );
        let e = load(&pack).err().expect("rejected");
        assert!(e.contains("assigns the module-level local `hums`"), "{e}");
    }

    #[test]
    fn global_writes_are_rejected_at_load() {
        let e = load(&in_update("last_user = me")).err().expect("rejected");
        assert!(e.contains("assigns a global"), "{e}");
    }

    #[test]
    fn module_tables_and_data_are_frozen() {
        for line in ["gun_del_sol.uses = me.step", "data.GUN_DEL_SOL_FIRING_TICKS[0] = 1", "math.floor = math.ceil"] {
            let e = play_error(load(&in_update(line)).unwrap()).expect("the write fails");
            assert!(e.contains("readonly"), "{line}: {e}");
        }
    }

    #[test]
    fn tables_captured_by_functions_are_frozen() {
        let pack = patched(
            "chips/gun_del_sol",
            &[
                ("local gun_del_sol = {", "local seen = {}\nlocal gun_del_sol = {"),
                (UPDATE, &format!("{UPDATE}    seen[1] = me.step\n")),
            ],
        );
        let e = play_error(load(&pack).unwrap()).expect("the write fails");
        assert!(e.contains("readonly"), "{e}");
    }

    #[test]
    fn nondeterministic_libraries_are_absent() {
        for call in [
            "math.random()",
            "math.sin(1)",
            "os.time()",
            "collectgarbage()",
            "coroutine.create(print)",
            "buffer.create(4)",
        ] {
            let e = play_error(load(&in_update(&format!("local _ = {call}"))).unwrap())
                .unwrap_or_else(|| panic!("{call} ran"));
            assert!(e.contains("attempt to"), "{call}: {e}");
        }
    }

    #[test]
    fn weak_tables_are_refused() {
        let content = load(&in_update("local _ = setmetatable({}, { __mode = \"k\" })")).unwrap();
        assert!(play_error(content).expect("refused").contains("weak tables"));
    }

    #[test]
    fn fractions_cannot_enter_battle_state() {
        let content =
            load(&patched("chips/gun_del_sol", &[("        s.timer = 6\n", "        s.timer = 13 / 2\n")])).unwrap();
        let e = play_error(content).expect("refused");
        assert!(e.contains("6.5 is not an integer"), "{e}");
    }

    #[test]
    fn runaway_scripts_stop() {
        let content = load(&in_update("while true do end")).unwrap();
        assert!(play_error(content).expect("stopped").contains("past its budget"));
    }

    #[test]
    fn the_vm_is_not_part_of_the_battle() {
        let tape = scenario::record(900);
        let shared = Content::luau().unwrap();
        let want = digests(&tape, Battle::with_content(scenario::setup(), shared.clone()));
        // Halfway, move the battle to a fresh VM, as restoring a snapshot
        // on another machine would.
        let mut b = Battle::with_content(scenario::setup(), shared.clone());
        let mut have = Vec::new();
        for (i, t) in tape.iter().enumerate() {
            if i == 450 {
                b.content = Content::luau().unwrap();
            }
            b.tick(&t.input, t.events.clone());
            have.push(b.digest());
        }
        assert_eq!(have, want, "a fresh VM continues the battle identically");
        // Interleave a second battle, playing a different tape, on the
        // same VM.
        let other = scenario::record(900);
        let (mut a, mut c) = (
            Battle::with_content(scenario::setup(), shared.clone()),
            Battle::with_content(scenario::setup(), shared.clone()),
        );
        let mut have = Vec::new();
        for (t, u) in tape.iter().zip(other.iter().skip(40)) {
            a.tick(&t.input, t.events.clone());
            have.push(a.digest());
            c.tick(
                &[u.input[1].clone(), u.input[0].clone()],
                TickEvents { exchange: u.events.exchange.clone(), ..u.events.clone() },
            );
        }
        let first = have.iter().zip(&want).position(|(a, b)| a != b);
        assert_eq!(first, None, "another battle on the same VM changes nothing");
    }

    /// An engine panic inside a script's API call unwinds through the Luau
    /// VM; the VM stays sound for every other battle using it.
    #[test]
    fn a_panic_inside_content_leaves_the_vm_sound() {
        let tape = scenario::record(900);
        let shared = Content::luau().unwrap();
        let want = digests(&tape, Battle::with_content(scenario::setup(), shared.clone()));
        let other: Vec<scenario::Tick> = scenario::record(900).into_iter().skip(20).collect();
        let (mut a, mut c) = (
            Battle::with_content(scenario::setup(), shared.clone()),
            Battle::with_content(scenario::setup(), shared.clone()),
        );
        let mut have = Vec::new();
        let mut panics = 0;
        for (t, u) in tape.iter().zip(&other) {
            a.tick(&t.input, t.events.clone());
            have.push(a.digest());
            // A Rust panic inside a Luau call: the reactive abort GunDelSol
            // calls isn't implemented and panics when a defense triggered.
            if let Some(p) = c.player(0) {
                if c.objects.get(p).action == 0x37 {
                    let actor = c.objects.get(p).actor.unwrap();
                    c.actors.get_mut(actor).requests |= crate::actor::request::ANTI_SWORD_TRIGGERED;
                }
            }
            if std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| c.tick(&u.input, u.events.clone()))).is_err() {
                panics += 1;
            }
        }
        let first = have.iter().zip(&want).position(|(x, y)| x != y);
        assert!(panics > 0, "the other battle should have panicked inside GunDelSol");
        assert_eq!(first, None, "a battle sharing the VM with {panics} panics diverged");
    }

    #[test]
    fn gc_timing_does_not_reach_the_battle() {
        let tape = scenario::record(900);
        let want = digests(&tape, Battle::with_content(scenario::setup(), Content::luau().unwrap()));
        let options = bn6_luau::Options { collect_garbage: true, ..Default::default() };
        let have = digests(&tape, Battle::with_content(scenario::setup(), Content::luau_with(options).unwrap()));
        assert_eq!(have, want);
    }
}
