//! Content-layer tests: the content packs' data agree with the engine's
//! generated tables, and every content runtime plays the GunDelSol
//! scenario tick for tick like the built-in kinds.

use crate::data::attacks;

/// The Luau data module the pack's `data/attacks.luau` must hold, rendered
/// from the engine's tables (which bn6-extract generates).
fn luau_attack_data() -> String {
    let mut s = String::from(
        "--!strict\n\
         -- Attack data for the slice, rendered from crates/bn6-battle/src/data/attacks_generated.rs\n\
         -- (itself generated by bn6-extract) by the bn6-battle test `luau_data_matches_the_engine`.\n\
         -- Do not edit; rerun that test with BN6_WRITE_CONTENT_DATA=1. Tables are keyed by the\n\
         -- game's 0-based indices.\n\n\
         export type SpriteId = { category: number, index: number }\n\
         export type AttachmentKind = {\n    sprite: SpriteId,\n    palette: number,\n    lift: number,\n    attach_point: number?,\n}\n\
         export type SunBeamLook = { sprite: number, palette: number }\n\n\
         local function attachment(category: number, index: number, palette: number, lift: number, attach_point: number?): AttachmentKind\n    \
         return { sprite = { category = category, index = index }, palette = palette, lift = lift, attach_point = attach_point }\nend\n\n\
         return {\n    -- Attachment kinds, the attachment's first parameter (`byte_80B8BD4`).\n    ATTACHMENTS = {\n",
    );
    for kind in 0..52u8 {
        let k = attacks::attachment(kind);
        let point = k.attach_point.map_or("nil".to_string(), |p| p.to_string());
        s += &format!(
            "        [{kind:#04x}] = attachment({:#04x}, {:#04x}, {}, {}, {point}),\n",
            k.sprite.category, k.sprite.index, k.palette, k.lift
        );
    }
    s += "    } :: { [number]: AttachmentKind },\n\n";
    s += "    -- GunDelSol's firing ticks by level (`dword_80EDBC8`).\n    GUN_DEL_SOL_FIRING_TICKS = { [0] = ";
    s += &(0..4).map(|l| attacks::gun_del_sol_firing_ticks(l).to_string()).collect::<Vec<_>>().join(", ");
    s += " },\n\n    -- GunDelSol's sun beam by [sun][level], sun = 0 or 1 (`byte_80EDBB8`).\n    GUN_DEL_SOL_BEAMS = {\n";
    for sun in [false, true] {
        let looks: Vec<String> = (0..4)
            .map(|l| {
                let b = attacks::gun_del_sol_beam(sun, l);
                format!("{{ sprite = {}, palette = {} }}", b.sprite, b.palette)
            })
            .collect();
        s += &format!("        [{}] = {{ [0] = {} }},\n", sun as u8, looks.join(", "));
    }
    s += "    } :: { [number]: { [number]: SunBeamLook } },\n\n";
    s += "    -- The sun beam's sprites, by `SunBeamLook.sprite` (`dword_80E5C28`).\n    SUN_BEAM_SPRITES = { [0] = ";
    s += &(0..2)
        .map(|i| {
            let id = attacks::sun_beam_sprite(i);
            format!("{{ category = {:#04x}, index = {:#04x} }}", id.category, id.index)
        })
        .collect::<Vec<_>>()
        .join(", ");
    s += " } :: { [number]: SpriteId },\n}\n";
    s
}

#[test]
fn luau_data_matches_the_engine() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../content/bn6/data/attacks.luau");
    let want = luau_attack_data();
    if std::env::var_os("BN6_WRITE_CONTENT_DATA").is_some() {
        std::fs::write(path, &want).unwrap();
    }
    let have = std::fs::read_to_string(path).unwrap_or_default();
    assert!(have == want, "content/bn6/data/attacks.luau is stale: rerun with BN6_WRITE_CONTENT_DATA=1");
}

#[cfg(feature = "rust-content")]
#[test]
fn rust_content_data_matches_the_engine() {
    use bn6_content_rust::data as rc;
    for kind in 0..52u8 {
        let (a, b) = (attacks::attachment(kind), rc::ATTACHMENTS[kind as usize]);
        assert_eq!((a.sprite, a.palette, a.lift, a.attach_point), (b.sprite, b.palette, b.lift, b.attach_point));
    }
    for level in 0..4u8 {
        assert_eq!(attacks::gun_del_sol_firing_ticks(level), rc::GUN_DEL_SOL_FIRING_TICKS[level as usize]);
        for sun in [false, true] {
            let (a, b) = (attacks::gun_del_sol_beam(sun, level), rc::GUN_DEL_SOL_BEAMS[sun as usize][level as usize]);
            assert_eq!((a.sprite, a.palette), (b.sprite, b.palette));
        }
    }
    for i in 0..2u8 {
        assert_eq!(attacks::sun_beam_sprite(i), rc::SUN_BEAM_SPRITES[i as usize]);
    }
}
