"""Combine content declarations for luau-lsp, which loads each definitions file separately."""

from pathlib import Path


def main():
    root = Path(__file__).resolve().parent.parent
    content = root / "content"
    engine = content / "nettai" / "core.d.luau"
    sources = [engine, *sorted(path for path in content.rglob("*.d.luau") if path != engine)]
    sections = [
        "-- Generated by .zed/generate-luau-definitions.py; edit the source declarations instead.\n"
        "-- Load together so references between the engine and pack types resolve.\n"
    ]
    for source in sources:
        sections.append(f"-- Source: {source.relative_to(root).as_posix()}\n{source.read_text(encoding='utf-8')}\n")

    destination = root / ".zed" / "luau-globals.d.luau"
    destination.write_text("\n".join(sections), encoding="utf-8")
    print(f"Wrote {destination.relative_to(root)} from {len(sources)} declaration files.")


if __name__ == "__main__":
    main()
