//! The slice's data tables. The engine's copies are generated by bn6-extract
//! (crates/bn6-battle/src/data/attacks_generated.rs); these are generated from
//! them, and a bn6-battle test checks they agree. Do not edit.

use bn6_content_api::SpriteId;

/// What an attachment looks like and where it sits on its owner.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AttachmentKind {
    pub sprite: SpriteId,
    pub palette: u8,
    /// Pixels the attachment is raised by (subtracted from its y and z).
    pub lift: i8,
    /// The owner's sprite attach point it follows (None: the owner's origin).
    pub attach_point: Option<u8>,
}

/// Which sun beam sprite and palette GunDelSol shows.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SunBeamLook {
    pub sprite: u8,
    pub palette: u8,
}

const fn a(category: u8, index: u8, palette: u8, lift: i8, attach_point: Option<u8>) -> AttachmentKind {
    AttachmentKind { sprite: SpriteId { category, index }, palette, lift, attach_point }
}

/// Attachment kinds, the attachment's first parameter (`byte_80B8BD4`).
pub static ATTACHMENTS: [AttachmentKind; 52] = [
    a(0x0c, 0x01, 0, 0, Some(7)),
    a(0x0c, 0x01, 1, 0, Some(7)),
    a(0x0c, 0x01, 2, 0, Some(7)),
    a(0x0c, 0x00, 0, 0, None),
    a(0x0c, 0x02, 0, 0, None),
    a(0x0c, 0x06, 0, 0, Some(16)),
    a(0x0c, 0x03, 0, 0, None),
    a(0x0c, 0x3b, 0, 0, Some(13)),
    a(0x0c, 0x3b, 3, 0, Some(13)),
    a(0x0c, 0x3b, 6, 0, Some(13)),
    a(0x0c, 0x3b, 9, 0, Some(13)),
    a(0x0c, 0x00, 0, 0, None),
    a(0x0c, 0x00, 0, 1, None),
    a(0x0c, 0x1d, 0, 0, Some(14)),
    a(0x0c, 0x0c, 0, 0, Some(15)),
    a(0x0c, 0x4f, 0, 0, None),
    a(0x0c, 0x00, 0, 0, None),
    a(0x0c, 0x00, 0, 0, None),
    a(0x0c, 0x50, 0, 0, None),
    a(0x0c, 0x18, 0, 0, Some(10)),
    a(0x0c, 0x08, 0, 0, Some(8)),
    a(0x0c, 0x19, 0, 0, Some(11)),
    a(0x0c, 0x29, 0, 0, Some(20)),
    a(0x0c, 0x2a, 0, 0, Some(23)),
    a(0x0c, 0x2b, 0, 0, Some(25)),
    a(0x0c, 0x36, 0, 0, None),
    a(0x0c, 0x37, 0, 0, None),
    a(0x0c, 0x38, 0, 0, None),
    a(0x0c, 0x00, 2, 0, None),
    a(0x0c, 0x40, 0, 0, Some(26)),
    a(0x0c, 0x1f, 0, 0, Some(22)),
    a(0x10, 0x5a, 0, 0, None),
    a(0x0c, 0x58, 0, 0, Some(19)),
    a(0x0c, 0x16, 0, 0, Some(9)),
    a(0x0c, 0x16, 1, 0, Some(9)),
    a(0x0c, 0x59, 0, 0, Some(12)),
    a(0x0c, 0x02, 3, 0, None),
    a(0x0c, 0x02, 1, 0, None),
    a(0x0c, 0x02, 2, 0, None),
    a(0x0c, 0x5d, 0, 0, Some(14)),
    a(0x0c, 0x5e, 0, 0, Some(14)),
    a(0x0c, 0x60, 0, 0, Some(14)),
    a(0x0c, 0x27, 0, 0, None),
    a(0x0c, 0x5f, 0, 0, Some(14)),
    a(0x0c, 0x61, 0, 0, Some(14)),
    a(0x0c, 0x02, 4, 0, None),
    a(0x10, 0x52, 0, 0, None),
    a(0x0c, 0x10, 0, 0, Some(25)),
    a(0x0c, 0x08, 0, -1, Some(8)),
    a(0x08, 0x13, 0, 0, None),
    a(0x0c, 0x43, 0, 0, Some(24)),
    a(0x0c, 0x5c, 0, 0, None),
];

/// GunDelSol's firing ticks by level (`dword_80EDBC8`).
pub static GUN_DEL_SOL_FIRING_TICKS: [u16; 4] = [60, 90, 120, 120];

/// GunDelSol's sun beam by [sun][level] (`byte_80EDBB8`).
pub static GUN_DEL_SOL_BEAMS: [[SunBeamLook; 4]; 2] = [[SunBeamLook { sprite: 0, palette: 0 }, SunBeamLook { sprite: 0, palette: 0 }, SunBeamLook { sprite: 0, palette: 0 }, SunBeamLook { sprite: 1, palette: 0 }], [SunBeamLook { sprite: 0, palette: 2 }, SunBeamLook { sprite: 0, palette: 2 }, SunBeamLook { sprite: 0, palette: 2 }, SunBeamLook { sprite: 1, palette: 3 }]];

/// The sun beam's sprites, by `SunBeamLook::sprite` (`dword_80E5C28`).
pub static SUN_BEAM_SPRITES: [SpriteId; 2] = [SpriteId { category: 0x0c, index: 0x3c }, SpriteId { category: 0x0c, index: 0x47 }];
