// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.

use super::SpriteId;
use super::attacks::{AttachmentKind, SunBeamLook};
use super::player::SecondaryElements;

/// The secondary elements a chip family adds to its attacks (`byte_80129E4`).
pub static FAMILY_ELEMENTS: [SecondaryElements; 16] = [SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x80), SecondaryElements(0x40), SecondaryElements(0x00), SecondaryElements(0x20), SecondaryElements(0x10), SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x00), SecondaryElements(0x00)];
/// Attachment kinds, the attachment's first parameter (`byte_80B8BD4`).
pub static ATTACHMENTS: [AttachmentKind; 52] = [
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x01 }, palette: 0, lift: 0, attach_point: Some(7) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x01 }, palette: 1, lift: 0, attach_point: Some(7) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x01 }, palette: 2, lift: 0, attach_point: Some(7) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x00 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x02 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x06 }, palette: 0, lift: 0, attach_point: Some(16) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x03 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x3b }, palette: 0, lift: 0, attach_point: Some(13) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x3b }, palette: 3, lift: 0, attach_point: Some(13) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x3b }, palette: 6, lift: 0, attach_point: Some(13) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x3b }, palette: 9, lift: 0, attach_point: Some(13) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x00 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x00 }, palette: 0, lift: 1, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x1d }, palette: 0, lift: 0, attach_point: Some(14) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x0c }, palette: 0, lift: 0, attach_point: Some(15) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x4f }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x00 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x00 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x50 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x18 }, palette: 0, lift: 0, attach_point: Some(10) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x08 }, palette: 0, lift: 0, attach_point: Some(8) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x19 }, palette: 0, lift: 0, attach_point: Some(11) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x29 }, palette: 0, lift: 0, attach_point: Some(20) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x2a }, palette: 0, lift: 0, attach_point: Some(23) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x2b }, palette: 0, lift: 0, attach_point: Some(25) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x36 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x37 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x38 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x00 }, palette: 2, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x40 }, palette: 0, lift: 0, attach_point: Some(26) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x1f }, palette: 0, lift: 0, attach_point: Some(22) },
    AttachmentKind { sprite: SpriteId { category: 0x10, index: 0x5a }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x58 }, palette: 0, lift: 0, attach_point: Some(19) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x16 }, palette: 0, lift: 0, attach_point: Some(9) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x16 }, palette: 1, lift: 0, attach_point: Some(9) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x59 }, palette: 0, lift: 0, attach_point: Some(12) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x02 }, palette: 3, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x02 }, palette: 1, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x02 }, palette: 2, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x5d }, palette: 0, lift: 0, attach_point: Some(14) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x5e }, palette: 0, lift: 0, attach_point: Some(14) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x60 }, palette: 0, lift: 0, attach_point: Some(14) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x27 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x5f }, palette: 0, lift: 0, attach_point: Some(14) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x61 }, palette: 0, lift: 0, attach_point: Some(14) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x02 }, palette: 4, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x10, index: 0x52 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x10 }, palette: 0, lift: 0, attach_point: Some(25) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x08 }, palette: 0, lift: -1, attach_point: Some(8) },
    AttachmentKind { sprite: SpriteId { category: 0x08, index: 0x13 }, palette: 0, lift: 0, attach_point: None },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x43 }, palette: 0, lift: 0, attach_point: Some(24) },
    AttachmentKind { sprite: SpriteId { category: 0x0c, index: 0x5c }, palette: 0, lift: 0, attach_point: None },
];
/// GunDelSol's firing ticks by level (`dword_80EDBC8`).
pub static GUN_DEL_SOL_FIRING_TICKS: [u8; 4] = [60, 90, 120, 120];
/// GunDelSol's sun beam by [sun][level] (`byte_80EDBB8`).
pub static GUN_DEL_SOL_BEAMS: [[SunBeamLook; 4]; 2] = [[SunBeamLook { sprite: 0, palette: 0 }, SunBeamLook { sprite: 0, palette: 0 }, SunBeamLook { sprite: 0, palette: 0 }, SunBeamLook { sprite: 1, palette: 0 }], [SunBeamLook { sprite: 0, palette: 2 }, SunBeamLook { sprite: 0, palette: 2 }, SunBeamLook { sprite: 0, palette: 2 }, SunBeamLook { sprite: 1, palette: 3 }]];
/// The sun beam's sprites, by `SunBeamLook::sprite` (`dword_80E5C28`).
pub static SUN_BEAM_SPRITES: [SpriteId; 2] = [SpriteId { category: 0x0c, index: 0x3c }, SpriteId { category: 0x0c, index: 0x47 }];
