// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.

/// Banner type by banner id / 4 (`pt_801EF84` records, byte 2).
pub static BANNER_TYPES: [u8; 47] = [0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 4, 0, 1, 2, 0, 1, 0, 0, 0, 3, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
/// Netbattle win banner id by navi (`byte_800A8EC`).
pub static WIN_BANNERS: [u8; 12] = [56, 144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184];
/// Netbattle lose banner id by navi (`byte_800A8C8`).
pub static LOSE_BANNERS: [u8; 12] = [8, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140];
