// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.

use super::BannerId;

/// Whether a banner stays up until removed, by banner id / 4.
pub static BANNER_HOLDS: [bool; 47] = [false, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
/// Netbattle win banner by navi (`byte_800A8EC`).
pub static WIN_BANNERS: [BannerId; 12] = [BannerId(0x38), BannerId(0x90), BannerId(0x94), BannerId(0x98), BannerId(0x9c), BannerId(0xa0), BannerId(0xa4), BannerId(0xa8), BannerId(0xac), BannerId(0xb0), BannerId(0xb4), BannerId(0xb8)];
/// Netbattle lose banner by navi (`byte_800A8C8`).
pub static LOSE_BANNERS: [BannerId; 12] = [BannerId(0x08), BannerId(0x64), BannerId(0x68), BannerId(0x6c), BannerId(0x70), BannerId(0x74), BannerId(0x78), BannerId(0x7c), BannerId(0x80), BannerId(0x84), BannerId(0x88), BannerId(0x8c)];
