// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.

use super::{PanelCondition, PanelOffset};

/// Collision type flags [alliance 0, alliance 1] by index (`byte_8019C7C`).
pub static COLLISION_TYPES: [[u32; 2]; 89] = [
    [0x00000000, 0x00000000], // 0x00
    [0x08410080, 0x04210080], // 0x01
    [0x55800200, 0xaa800200], // 0x02
    [0x51800100, 0xa2800100], // 0x03
    [0x80000080, 0x40000080], // 0x04
    [0x15800000, 0x2a800000], // 0x05
    [0x80000082, 0x40000082], // 0x06
    [0x80002080, 0x40002080], // 0x07
    [0x80000090, 0x40000090], // 0x08
    [0x80000180, 0x40000180], // 0x09
    [0x80000088, 0x40000088], // 0x0a
    [0x80000084, 0x40000084], // 0x0b
    [0x20010080, 0x10010080], // 0x0c
    [0x55840000, 0xaa840000], // 0x0d
    [0x00810082, 0x00810082], // 0x0e
    [0xff800002, 0xff800002], // 0x0f
    [0x08510080, 0x04310080], // 0x10
    [0x80002480, 0x40002480], // 0x11
    [0x80000880, 0x40000880], // 0x12
    [0x02010080, 0x01010080], // 0x13
    [0x55800000, 0xaa800000], // 0x14
    [0x8000008a, 0x4000008a], // 0x15
    [0x80000086, 0x40000086], // 0x16
    [0x8000008e, 0x4000008e], // 0x17
    [0x50000000, 0xa0000000], // 0x18
    [0x8000008c, 0x4000008c], // 0x19
    [0x8000009e, 0x4000009e], // 0x1a
    [0x800040a0, 0x400040a0], // 0x1b
    [0x80002088, 0x40002088], // 0x1c
    [0x8000009c, 0x4000009c], // 0x1d
    [0x00004280, 0x00004280], // 0x1e
    [0x80040082, 0x40040082], // 0x1f
    [0x80000888, 0x40000888], // 0x20
    [0x8004008a, 0x4004008a], // 0x21
    [0xc004808e, 0xc004808e], // 0x22
    [0x00080000, 0x00080000], // 0x23
    [0x80000c88, 0x40000c88], // 0x24
    [0x80000480, 0x40000480], // 0x25
    [0xc0040088, 0xc0040088], // 0x26
    [0xc0048082, 0xc0048082], // 0x27
    [0x80002086, 0x40002086], // 0x28
    [0x02010082, 0x01010082], // 0x29
    [0x3d800000, 0x3e800000], // 0x2a
    [0x80000488, 0x40000488], // 0x2b
    [0x8000408c, 0x4000408c], // 0x2c
    [0x8000408a, 0x4000408a], // 0x2d
    [0x80004086, 0x40004086], // 0x2e
    [0x80004088, 0x40004088], // 0x2f
    [0x8000408e, 0x4000408e], // 0x30
    [0x80005084, 0x40005084], // 0x31
    [0x80005080, 0x40005080], // 0x32
    [0xc004000e, 0xc004000e], // 0x33
    [0x80004084, 0x40004084], // 0x34
    [0x08410082, 0x04210082], // 0x35
    [0x80004082, 0x40004082], // 0x36
    [0x0201008a, 0x0101008a], // 0x37
    [0x0f800000, 0x0f800000], // 0x38
    [0x08510082, 0x04310082], // 0x39
    [0x0841008a, 0x0421008a], // 0x3a
    [0x20010082, 0x10010082], // 0x3b
    [0x8000408a, 0x4000408a], // 0x3c
    [0x00000080, 0x00000080], // 0x3d
    [0x02110080, 0x01110080], // 0x3e
    [0x0851008a, 0x0431008a], // 0x3f
    [0x20012080, 0x10012080], // 0x40
    [0x04000000, 0x08000000], // 0x41
    [0x80002090, 0x40002090], // 0x42
    [0x00040080, 0x00040080], // 0x43
    [0x20050080, 0x10050080], // 0x44
    [0x8000208a, 0x4000208a], // 0x45
    [0x800140a0, 0x400140a0], // 0x46
    [0x800000a0, 0x400000a0], // 0x47
    [0xc0040080, 0xc0040080], // 0x48
    [0x3f800000, 0x3f800000], // 0x49
    [0x80000482, 0x40000482], // 0x4a
    [0x80000c88, 0x40000c88], // 0x4b
    [0x02014082, 0x01014082], // 0x4c
    [0x55000200, 0xaa000200], // 0x4d
    [0x02010088, 0x01010088], // 0x4e
    [0x0081008a, 0x0081008a], // 0x4f
    [0x08412080, 0x04212080], // 0x50
    [0x08410092, 0x04210092], // 0x51
    [0x80001080, 0x40001080], // 0x52
    [0x08412082, 0x04212082], // 0x53
    [0x80002092, 0x40002092], // 0x54
    [0x0841009a, 0x0421009a], // 0x55
    [0x80000884, 0x40000884], // 0x56
    [0x800000b2, 0x400000b2], // 0x57
    [0xc0044080, 0xc0044080], // 0x58
];
/// Region shapes: the panels a hit covers, relative to its panel, dx toward the facing side (`PanelOffsetListsPointerTable`).
pub static REGIONS: [&[PanelOffset]; 47] = [
    &[], // 0
    &[PanelOffset { dx: 0, dy: 0 }], // 1
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }], // 2
    &[PanelOffset { dx: 1, dy: 0 }], // 3
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }], // 4
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }], // 5
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }], // 6
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 3, dy: 0 }], // 7
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 4, dy: 0 }, PanelOffset { dx: 5, dy: 0 }], // 8
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: -1, dy: 0 }], // 9
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: -1, dy: 0 }], // 10
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: -1, dy: -1 }], // 11
    &[PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: -1, dy: -1 }], // 12
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 1 }], // 13
    &[PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 1 }], // 14
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: -1, dy: -1 }], // 15
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: -1, dy: -1 }], // 16
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 1 }], // 17
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }], // 18
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: 1, dy: 1 }], // 19
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 0 }], // 20
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 1, dy: 0 }], // 21
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }], // 22
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 1 }], // 23
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -1 }], // 24
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: 1 }], // 25
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 2, dy: 1 }], // 26
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 2, dy: 1 }, PanelOffset { dx: 3, dy: -1 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 3, dy: 1 }], // 27
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 2, dy: 1 }, PanelOffset { dx: 3, dy: -1 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 3, dy: 1 }, PanelOffset { dx: 4, dy: -1 }, PanelOffset { dx: 4, dy: 0 }, PanelOffset { dx: 4, dy: 1 }], // 28
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: -1, dy: 0 }], // 29
    &[PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: -1, dy: 0 }], // 30
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }], // 31
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 4, dy: 0 }], // 32
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 2, dy: 1 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 3, dy: -1 }, PanelOffset { dx: 3, dy: 1 }], // 33
    &[PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 1 }], // 34
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 3, dy: -1 }, PanelOffset { dx: 4, dy: -1 }, PanelOffset { dx: 5, dy: -1 }, PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 4, dy: 0 }, PanelOffset { dx: 5, dy: 0 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: 1 }, PanelOffset { dx: 3, dy: 1 }, PanelOffset { dx: 4, dy: 1 }, PanelOffset { dx: 5, dy: 1 }], // 35
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: -2, dy: 1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: 0, dy: 1 }], // 36
    &[PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: 1 }], // 37
    &[PanelOffset { dx: -2, dy: -2 }, PanelOffset { dx: -1, dy: -2 }, PanelOffset { dx: 0, dy: -2 }, PanelOffset { dx: 1, dy: -2 }, PanelOffset { dx: 2, dy: -2 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: -2, dy: 0 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: -2, dy: 1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: 1 }, PanelOffset { dx: -2, dy: 2 }, PanelOffset { dx: -1, dy: 2 }, PanelOffset { dx: 0, dy: 2 }, PanelOffset { dx: 1, dy: 2 }, PanelOffset { dx: 2, dy: 2 }], // 38
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 3, dy: -1 }, PanelOffset { dx: 4, dy: -1 }, PanelOffset { dx: 5, dy: -1 }, PanelOffset { dx: 5, dy: 0 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: 1 }, PanelOffset { dx: 3, dy: 1 }, PanelOffset { dx: 4, dy: 1 }, PanelOffset { dx: 5, dy: 1 }], // 39
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 2, dy: 1 }], // 40
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 1, dy: 1 }, PanelOffset { dx: 2, dy: 1 }], // 41
    &[PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 1, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 4, dy: 0 }, PanelOffset { dx: 5, dy: 0 }], // 42
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: -2, dy: 0 }], // 43
    &[PanelOffset { dx: 5, dy: -2 }, PanelOffset { dx: 4, dy: -2 }, PanelOffset { dx: 3, dy: -2 }, PanelOffset { dx: 2, dy: -2 }, PanelOffset { dx: 1, dy: -2 }, PanelOffset { dx: 0, dy: -2 }, PanelOffset { dx: -1, dy: -2 }, PanelOffset { dx: -2, dy: -2 }, PanelOffset { dx: -3, dy: -2 }, PanelOffset { dx: -4, dy: -2 }, PanelOffset { dx: -5, dy: -2 }, PanelOffset { dx: 5, dy: 2 }, PanelOffset { dx: 4, dy: 2 }, PanelOffset { dx: 3, dy: 2 }, PanelOffset { dx: 2, dy: 2 }, PanelOffset { dx: 1, dy: 2 }, PanelOffset { dx: 0, dy: 2 }, PanelOffset { dx: -1, dy: 2 }, PanelOffset { dx: -2, dy: 2 }, PanelOffset { dx: -3, dy: 2 }, PanelOffset { dx: -4, dy: 2 }, PanelOffset { dx: -5, dy: 2 }, PanelOffset { dx: 5, dy: -1 }, PanelOffset { dx: 4, dy: -1 }, PanelOffset { dx: 3, dy: -1 }, PanelOffset { dx: 2, dy: -1 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -3, dy: -1 }, PanelOffset { dx: -4, dy: -1 }, PanelOffset { dx: -5, dy: -1 }, PanelOffset { dx: 5, dy: 1 }, PanelOffset { dx: 4, dy: 1 }, PanelOffset { dx: 3, dy: 1 }, PanelOffset { dx: 2, dy: 1 }, PanelOffset { dx: -2, dy: 1 }, PanelOffset { dx: -3, dy: 1 }, PanelOffset { dx: -4, dy: 1 }, PanelOffset { dx: -5, dy: 1 }, PanelOffset { dx: 5, dy: 0 }, PanelOffset { dx: 4, dy: 0 }, PanelOffset { dx: 3, dy: 0 }, PanelOffset { dx: 2, dy: 0 }, PanelOffset { dx: -2, dy: 0 }, PanelOffset { dx: -3, dy: 0 }, PanelOffset { dx: -4, dy: 0 }, PanelOffset { dx: -5, dy: 0 }], // 44
    &[PanelOffset { dx: 0, dy: 0 }, PanelOffset { dx: 0, dy: -2 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 0, dy: 2 }], // 45
    &[PanelOffset { dx: 0, dy: -2 }, PanelOffset { dx: 0, dy: -1 }, PanelOffset { dx: 0, dy: 1 }, PanelOffset { dx: 0, dy: 2 }], // 46
];
/// Whole-field regions (region 0x80 + i): every panel meeting the condition.
pub static FIELD_REGIONS: [PanelCondition; 9] = [PanelCondition { require: 0x0, forbid: 0x0 }, PanelCondition { require: 0x0, forbid: 0x20 }, PanelCondition { require: 0x20, forbid: 0x0 }, PanelCondition { require: 0x10, forbid: 0x0 }, PanelCondition { require: 0x400000, forbid: 0x0 }, PanelCondition { require: 0x200000, forbid: 0x0 }, PanelCondition { require: 0x0, forbid: 0x600000 }, PanelCondition { require: 0x10, forbid: 0x20 }, PanelCondition { require: 0x30, forbid: 0x0 }];
/// Extra damage multiplier by [receiver element][hitter element] (`byte_3007444`, which the game indexes as r*5+h).
pub static ELEMENT_WEAKNESS: [[u8; 6]; 6] = [[0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]];
