// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.

use super::PanelOffset;
use super::lockon::LockonSearch;

/// Column shifts toward the user tried when no panel next to the target fits (`byte_8026735`).
pub static COLUMN_SHIFTS: [i8; 4] = [-1, -2, -3, -4];
/// The searching lock-on modes: panels next to the target, dx toward the user's front.
pub static SEARCHES: [LockonSearch; 12] = [
    LockonSearch { mode: 0x02, offsets: &[PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }], prefers_middle_row: false },
    LockonSearch { mode: 0x03, offsets: &[PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: -1, dy: 0 }], prefers_middle_row: true },
    LockonSearch { mode: 0x04, offsets: &[PanelOffset { dx: -2, dy: 0 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: -2, dy: 1 }, PanelOffset { dx: -1, dy: 1 }], prefers_middle_row: false },
    LockonSearch { mode: 0x05, offsets: &[PanelOffset { dx: -3, dy: 0 }, PanelOffset { dx: -2, dy: 0 }, PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: -3, dy: -1 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: -3, dy: 1 }, PanelOffset { dx: -2, dy: 1 }, PanelOffset { dx: -1, dy: 1 }], prefers_middle_row: false },
    LockonSearch { mode: 0x06, offsets: &[PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: -1, dy: -1 }, PanelOffset { dx: -1, dy: 1 }, PanelOffset { dx: -2, dy: 0 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -2, dy: 1 }], prefers_middle_row: true },
    LockonSearch { mode: 0x07, offsets: &[PanelOffset { dx: -2, dy: 0 }], prefers_middle_row: false },
    LockonSearch { mode: 0x08, offsets: &[PanelOffset { dx: -3, dy: 0 }], prefers_middle_row: false },
    LockonSearch { mode: 0x09, offsets: &[PanelOffset { dx: -2, dy: 0 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -2, dy: 1 }], prefers_middle_row: true },
    LockonSearch { mode: 0x0c, offsets: &[PanelOffset { dx: -1, dy: 0 }], prefers_middle_row: false },
    LockonSearch { mode: 0x0d, offsets: &[PanelOffset { dx: -1, dy: 0 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -2, dy: 1 }, PanelOffset { dx: 1, dy: -1 }, PanelOffset { dx: 1, dy: 1 }], prefers_middle_row: false },
    LockonSearch { mode: 0x0f, offsets: &[PanelOffset { dx: -3, dy: 0 }, PanelOffset { dx: -4, dy: 0 }, PanelOffset { dx: -3, dy: -1 }, PanelOffset { dx: -3, dy: 1 }, PanelOffset { dx: -4, dy: -1 }, PanelOffset { dx: -4, dy: 1 }, PanelOffset { dx: -2, dy: 0 }, PanelOffset { dx: -2, dy: -1 }, PanelOffset { dx: -2, dy: 1 }], prefers_middle_row: false },
    LockonSearch { mode: 0x10, offsets: &[PanelOffset { dx: -3, dy: 0 }], prefers_middle_row: true },
];
