// Generated by bn6-extract from MEGAMAN6_FXXBR6E. Do not edit.

use super::{Element, RockKind, SpriteId};

/// Rocks by variant, the rock's first parameter (`byte_80CF934`).
pub static ROCKS: [RockKind; 4] = [
    RockKind { anim: 1, hp: 1, element: Element::Null, debris_palette: 0, break_sound: 0x0097, name_id: 0x00d0 },
    RockKind { anim: 1, hp: 200, element: Element::Null, debris_palette: 0, break_sound: 0x0097, name_id: 0x00d0 },
    RockKind { anim: 1, hp: 500, element: Element::Null, debris_palette: 0, break_sound: 0x0097, name_id: 0x00d0 },
    RockKind { anim: 2, hp: 200, element: Element::Aqua, debris_palette: 1, break_sound: 0x00d9, name_id: 0x00d1 },
];
/// The sprite an absorbed obstacle flies with, by obstacle kind (`byte_80E98C0`).
pub static ABSORBED_SPRITES: [SpriteId; 15] = [
    SpriteId { category: 0x04, index: 0x09 },
    SpriteId { category: 0x0c, index: 0x24 },
    SpriteId { category: 0x0c, index: 0x23 },
    SpriteId { category: 0x0c, index: 0x30 },
    SpriteId { category: 0x10, index: 0x00 },
    SpriteId { category: 0x10, index: 0x08 },
    SpriteId { category: 0x04, index: 0x18 },
    SpriteId { category: 0x04, index: 0x0a },
    SpriteId { category: 0x0c, index: 0x34 },
    SpriteId { category: 0x0c, index: 0x35 },
    SpriteId { category: 0x04, index: 0x0d },
    SpriteId { category: 0x10, index: 0x00 },
    SpriteId { category: 0x0c, index: 0x41 },
    SpriteId { category: 0x04, index: 0x05 },
    SpriteId { category: 0x0c, index: 0x41 },
];
