//! Static recompiler: translates the game's Thumb/ARM code into Rust.
//!
//! Usage: recomp <rom> <data-dir> <out-src-dir>

mod discover;
mod emit;
mod image;
mod liveness;
mod syms;

use discover::{Ctx, Func, Ins, discover};
use gba_isa::thumb::Thumb;
use image::{Image, Overlay};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::PathBuf;
use syms::{Mode, Syms};

/// Functions per generated module.
const MODULE_SIZE: usize = 400;

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in",
    "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super",
    "trait", "true", "type", "unsafe", "use", "where", "while", "async", "await", "dyn", "abstract", "become", "box",
    "do", "final", "macro", "override", "priv", "typeof", "unsized", "virtual", "yield", "try", "gen",
];

fn sanitize(name: &str) -> String {
    let mut s: String = name.chars().map(|ch| if ch.is_ascii_alphanumeric() || ch == '_' { ch } else { '_' }).collect();
    if s.chars().next().is_none_or(|ch| ch.is_ascii_digit()) {
        s.insert(0, '_');
    }
    if RUST_KEYWORDS.contains(&s.as_str()) {
        s.push('_');
    }
    s
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 4 {
        eprintln!("usage: recomp <rom> <data-dir> <out-src-dir>");
        std::process::exit(2);
    }
    let rom = std::fs::read(&args[1]).expect("reading ROM");
    let data_dir = PathBuf::from(&args[2]);
    let out_dir = PathBuf::from(&args[3]);

    let syms = Syms::load(&data_dir);
    let image = Image {
        rom,
        overlays: vec![
            // Boot copy of the IWRAM routines (IWRAMRoutinesROMLocation).
            Overlay { vma: 0x0300_5B00, lma: 0x081D_6000, len: 0x0300_8000 - 0x0300_5B00 },
            // m4a SoundMainRAM, copied to IWRAM by the sound driver's init.
            Overlay { vma: 0x0300_5700, lma: 0x0814_DC88, len: 0x400 },
        ],
    };

    let mut entries: BTreeMap<u32, Mode> = syms.funcs.iter().map(|(a, (m, _))| (*a, *m)).collect();
    // SoundMainRAM runs from its IWRAM copy.
    entries.insert(0x0300_5700, Mode::Thumb);

    // Discover to a fixed point: new call targets become functions.
    let mut funcs: BTreeMap<u32, Func>;
    loop {
        let ctx = Ctx { image: &image, entries: &entries, code_refs: &syms.code_refs };
        funcs = entries.iter().map(|(&a, &m)| (a, discover(&ctx, a, m))).collect();
        let mut new = BTreeMap::new();
        for f in funcs.values() {
            for &(t, m) in &f.calls {
                if !entries.contains_key(&t) {
                    new.insert(t, m);
                }
            }
        }
        if new.is_empty() {
            break;
        }
        eprintln!("discovered {} new call targets", new.len());
        entries.extend(new);
    }

    // Names.
    let mut idents: BTreeMap<u32, String> = BTreeMap::new();
    let mut names: BTreeMap<u32, String> = BTreeMap::new();
    let mut used: BTreeSet<String> = BTreeSet::new();
    for &a in entries.keys() {
        let name = syms
            .funcs
            .get(&a)
            .map(|(_, n)| n.clone())
            .or_else(|| syms.label(a).map(|s| s.to_string()))
            .unwrap_or_else(|| format!("sub_{a:X}"));
        let mut ident = sanitize(&name);
        if used.contains(&ident) {
            ident = format!("{ident}_{a:X}");
        }
        used.insert(ident.clone());
        idents.insert(a, ident);
        names.insert(a, name);
    }

    let emitter = emit::Emitter { image: &image, syms: &syms, idents: &idents };
    std::fs::create_dir_all(&out_dir).unwrap();

    let mut report = String::new();
    let mut n_problems = 0;
    let mut n_insns = 0;
    let all: Vec<&Func> = funcs.values().collect();
    let mut mod_names = Vec::new();
    for (mi, chunk) in all.chunks(MODULE_SIZE).enumerate() {
        let mod_name = format!("m{mi:02}_{:07x}", chunk[0].entry & 0x0fff_ffff);
        let mut out = String::new();
        writeln!(out, "// Generated by recomp from the ROM. Do not edit.").unwrap();
        writeln!(out, "use crate::*;").unwrap();
        writeln!(out, "use gba_rt::*;").unwrap();
        writeln!(out).unwrap();
        for f in chunk {
            n_insns += f.insns.len();
            let live = match f.mode {
                Mode::Thumb => thumb_liveness(f),
                Mode::Arm => BTreeMap::new(),
            };
            emitter.emit_function(f, &names[&f.entry], &live, &mut out);
            for p in &f.problems {
                n_problems += 1;
                writeln!(report, "{:#010x} {}: {p}", f.entry, names[&f.entry]).unwrap();
            }
            for j in &f.computed_jumps {
                writeln!(report, "{:#010x} {}: computed jump at {j:#010x}", f.entry, names[&f.entry]).unwrap();
            }
        }
        std::fs::write(out_dir.join(format!("{mod_name}.rs")), out).unwrap();
        mod_names.push(mod_name);
    }

    let mut lib = String::new();
    writeln!(lib, "//! Machine-translated game code. Generated by recomp from the ROM; do not edit.").unwrap();
    writeln!(lib, "#![allow(unused, non_snake_case, non_upper_case_globals, clippy::all)]").unwrap();
    writeln!(lib).unwrap();
    writeln!(lib, "use gba_rt::Cpu;").unwrap();
    writeln!(lib).unwrap();
    for m in &mod_names {
        writeln!(lib, "mod {m};").unwrap();
        writeln!(lib, "pub use {m}::*;").unwrap();
    }
    writeln!(lib).unwrap();
    writeln!(lib, "/// Every translated function, sorted by address.").unwrap();
    writeln!(lib, "pub static FUNCTIONS: [(u32, fn(&mut Cpu)); {}] = [", idents.len()).unwrap();
    for (a, i) in &idents {
        writeln!(lib, "    ({a:#010x}, {i}),").unwrap();
    }
    writeln!(lib, "];").unwrap();
    writeln!(lib).unwrap();
    writeln!(lib, "/// The translated function entered at `addr`, if any.").unwrap();
    writeln!(lib, "pub fn lookup(addr: u32) -> Option<fn(&mut Cpu)> {{").unwrap();
    writeln!(lib, "    FUNCTIONS.binary_search_by_key(&addr, |&(a, _)| a).ok().map(|i| FUNCTIONS[i].1)").unwrap();
    writeln!(lib, "}}").unwrap();
    writeln!(lib).unwrap();
    writeln!(lib, "/// The disassembly name of the function entered at `addr`.").unwrap();
    writeln!(lib, "pub fn name(addr: u32) -> Option<&'static str> {{").unwrap();
    writeln!(lib, "    NAMES.binary_search_by_key(&addr, |&(a, _)| a).ok().map(|i| NAMES[i].1)").unwrap();
    writeln!(lib, "}}").unwrap();
    writeln!(lib).unwrap();
    writeln!(lib, "static NAMES: [(u32, &str); {}] = [", names.len()).unwrap();
    for (a, n) in &names {
        writeln!(lib, "    ({a:#010x}, {n:?}),").unwrap();
    }
    writeln!(lib, "];").unwrap();
    std::fs::write(out_dir.join("lib.rs"), lib).unwrap();
    std::fs::write(out_dir.join("../recomp-report.txt"), &report).unwrap();
    eprintln!(
        "{} functions, {} instructions, {} modules, {} problems (see recomp-report.txt)",
        funcs.len(),
        n_insns,
        mod_names.len(),
        n_problems
    );
}

fn thumb_liveness(f: &Func) -> BTreeMap<u32, u8> {
    let is_call_idiom = |addr: u32| -> bool {
        matches!(f.insns.get(&addr), Some(Ins::T(Thumb::Bx { .. } | Thumb::HiMov { rd: 15, .. })))
            && matches!(f.insns.get(&(addr.wrapping_sub(2))), Some(Ins::T(Thumb::HiMov { rd: 14, rs: 15 })))
    };
    let is_call = |addr: u32| matches!(f.insns.get(&addr), Some(Ins::TBl { .. })) || is_call_idiom(addr);
    let succs = |addr: u32| -> (Vec<u32>, bool) {
        let ins = &f.insns[&addr];
        let next = addr + ins.size();
        let fall = |v: &mut Vec<u32>| -> bool {
            if f.insns.contains_key(&next) {
                v.push(next);
                false
            } else {
                true
            }
        };
        let mut v = Vec::new();
        let target = |t: u32, v: &mut Vec<u32>| -> bool {
            if f.leaders.contains(&t) {
                v.push(t);
                false
            } else {
                true
            }
        };
        let exits = match ins {
            Ins::TBl { .. } => fall(&mut v),
            Ins::T(t) => match *t {
                Thumb::B { offset } => target(addr.wrapping_add(4).wrapping_add(offset as u32), &mut v),
                Thumb::BCond { offset, .. } => {
                    let e1 = target(addr.wrapping_add(4).wrapping_add(offset as u32), &mut v);
                    let e2 = fall(&mut v);
                    e1 || e2
                }
                Thumb::Bx { .. } | Thumb::HiMov { rd: 15, .. } if is_call_idiom(addr) => fall(&mut v),
                Thumb::Bx { .. }
                | Thumb::HiMov { rd: 15, .. }
                | Thumb::HiAdd { rd: 15, .. }
                | Thumb::Pop { pc: true, .. }
                | Thumb::Undefined(_)
                | Thumb::BlHi { .. }
                | Thumb::BlLo { .. } => true,
                _ => fall(&mut v),
            },
            Ins::A(_) => true,
        };
        (v, exits)
    };
    liveness::thumb_live_out(f, is_call, succs)
}
