// Generated by recomp from the ROM. Do not edit.
use crate::*;
use gba_rt::*;

/// `sub_814FD54` (0x0814fd54, thumb)
pub fn sub_814FD54(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fd54;
    loop {
        match pc {
            0x0814fd54 => {
                let a = c.r[13].wrapping_sub(0x4); c.st32(a, c.r[14]); c.r[13] = a; // 814fd54: push {lr}
                c.r[2] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fd56: ldr r2, [r1, #0x40]
                c.r[3] = c.ld8(c.r[2]); // 814fd58: ldrb r3, [r2, #0x0]
                c.r[2] = c.r[2].wrapping_add(0x1); // 814fd5a: add r2, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[2]); // 814fd5c: str r2, [r1, #0x40]
                c.r[2] = 0x081c06c0; // =off_81C06C0 // 814fd5e: ldr r2, [pc, #0x10] // 0x0814fd70
                c.r[3] = c.r[3] << 2; // 814fd60: lsl r3, r3, #0x2
                c.r[3] = c.adds(c.r[3], c.r[2]); // 814fd62: add r3, r3, r2
                c.r[2] = c.ld32(c.r[3]); // 814fd64: ldr r2, [r3, #0x0]
                c.r[14] = 0x0814fd6b; c.ret = 0x0814fd6a; sub_814DA68(c); if c.pc != 0x0814fd6a { pc = c.pc; continue; } // 814fd66: bl sub_814DA68
                let a = c.r[13]; c.r[0] = c.ld32(a); c.r[13] = a.wrapping_add(0x4); // 814fd6a: pop {r0}
                pc = c.r[0] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fd6c: bx r0
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FD74` (0x0814fd74, thumb)
pub fn sub_814FD74(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fd74;
    loop {
        match pc {
            0x0814fd74 => {
                let a = c.r[13].wrapping_sub(0x4); c.st32(a, c.r[14]); c.r[13] = a; // 814fd74: push {lr}
                c.r[2] = 0x03005570; // =off_3005570 // 814fd76: ldr r2, [pc, #0xc] // 0x0814fd84
                c.r[2] = c.ld32(c.r[2]); // 814fd78: ldr r2, [r2, #0x0]
                c.r[14] = 0x0814fd7f; c.ret = 0x0814fd7e; sub_814DA68(c); if c.pc != 0x0814fd7e { pc = c.pc; continue; } // 814fd7a: bl sub_814DA68
                let a = c.r[13]; c.r[0] = c.ld32(a); c.r[13] = a.wrapping_add(0x4); // 814fd7e: pop {r0}
                pc = c.r[0] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fd80: bx r0
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FD88` (0x0814fd88, thumb)
pub fn sub_814FD88(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fd88;
    loop {
        match pc {
            0x0814fd88 => {
                let a = c.r[13].wrapping_sub(0x8); c.st32(a, c.r[4]); c.st32(a.wrapping_add(0x4), c.r[14]); c.r[13] = a; // 814fd88: push {r4,lr}
                c.r[3] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fd8a: ldr r3, [r1, #0x40]
                c.r[2] = c.ld8(c.r[3]); // 814fd8c: ldrb r2, [r3, #0x0]
                c.r[0] = 0xffffff00; // 814fd8e: ldr r0, [pc, #0x30] // 0x0814fdc0
                c.r[4] = c.r[4] & c.r[0]; // 814fd90: and r4, r0
                c.r[4] = c.r[4] | c.r[2]; // 814fd92: orr r4, r2
                c.r[0] = c.ld8(c.r[3].wrapping_add(0x1)); // 814fd94: ldrb r0, [r3, #0x1]
                c.r[0] = c.r[0] << 8; // 814fd96: lsl r0, r0, #0x8
                c.r[2] = 0xffff00ff; // 814fd98: ldr r2, [pc, #0x28] // 0x0814fdc4
                c.r[4] = c.r[4] & c.r[2]; // 814fd9a: and r4, r2
                c.r[4] = c.r[4] | c.r[0]; // 814fd9c: orr r4, r0
                c.r[0] = c.ld8(c.r[3].wrapping_add(0x2)); // 814fd9e: ldrb r0, [r3, #0x2]
                c.r[0] = c.r[0] << 16; // 814fda0: lsl r0, r0, #0x10
                c.r[2] = 0xff00ffff; // 814fda2: ldr r2, [pc, #0x24] // 0x0814fdc8
                c.r[4] = c.r[4] & c.r[2]; // 814fda4: and r4, r2
                c.r[4] = c.r[4] | c.r[0]; // 814fda6: orr r4, r0
                c.r[0] = c.ld8(c.r[3].wrapping_add(0x3)); // 814fda8: ldrb r0, [r3, #0x3]
                c.r[0] = c.r[0] << 24; // 814fdaa: lsl r0, r0, #0x18
                c.r[2] = 0x00ffffff; // 814fdac: ldr r2, [pc, #0x1c] // 0x0814fdcc
                c.r[4] = c.r[4] & c.r[2]; // 814fdae: and r4, r2
                c.r[4] = c.r[4] | c.r[0]; // 814fdb0: orr r4, r0
                c.st32(c.r[1].wrapping_add(0x28), c.r[4]); // 814fdb2: str r4, [r1, #0x28]
                c.r[3] = c.adds(c.r[3], 0x4); // 814fdb4: add r3, #0x4
                c.st32(c.r[1].wrapping_add(0x40), c.r[3]); // 814fdb6: str r3, [r1, #0x40]
                let a = c.r[13]; c.r[4] = c.ld32(a); c.r[13] = a.wrapping_add(0x4); // 814fdb8: pop {r4}
                let a = c.r[13]; c.r[0] = c.ld32(a); c.r[13] = a.wrapping_add(0x4); // 814fdba: pop {r0}
                pc = c.r[0] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fdbc: bx r0
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FDD0` (0x0814fdd0, thumb)
pub fn sub_814FDD0(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fdd0;
    loop {
        match pc {
            0x0814fdd0 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fdd0: ldr r0, [r1, #0x40]
                c.r[2] = c.ld8(c.r[0]); // 814fdd2: ldrb r2, [r0, #0x0]
                c.r[0] = c.r[1].wrapping_add(0); // 814fdd4: add r0, r1, #0
                c.r[0] = c.r[0].wrapping_add(0x24); // 814fdd6: add r0, #0x24
                c.st8(c.r[0], c.r[2]); // 814fdd8: strb r2, [r0, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fdda: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fddc: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fdde: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fde0: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FDE4` (0x0814fde4, thumb)
pub fn sub_814FDE4(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fde4;
    loop {
        match pc {
            0x0814fde4 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fde4: ldr r0, [r1, #0x40]
                c.r[2] = c.ld8(c.r[0]); // 814fde6: ldrb r2, [r0, #0x0]
                c.r[0] = c.r[1].wrapping_add(0); // 814fde8: add r0, r1, #0
                c.r[0] = c.r[0].wrapping_add(0x2c); // 814fdea: add r0, #0x2c
                c.st8(c.r[0], c.r[2]); // 814fdec: strb r2, [r0, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fdee: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fdf0: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fdf2: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fdf4: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FDF8` (0x0814fdf8, thumb)
pub fn sub_814FDF8(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fdf8;
    loop {
        match pc {
            0x0814fdf8 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fdf8: ldr r0, [r1, #0x40]
                c.r[0] = c.ld8(c.r[0]); // 814fdfa: ldrb r0, [r0, #0x0]
                c.r[2] = c.r[1].wrapping_add(0); // 814fdfc: add r2, r1, #0
                c.r[2] = c.r[2].wrapping_add(0x2d); // 814fdfe: add r2, #0x2d
                c.st8(c.r[2], c.r[0]); // 814fe00: strb r0, [r2, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe02: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe04: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe06: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe08: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FE0C` (0x0814fe0c, thumb)
pub fn sub_814FE0C(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe0c;
    loop {
        match pc {
            0x0814fe0c => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe0c: ldr r0, [r1, #0x40]
                c.r[0] = c.ld8(c.r[0]); // 814fe0e: ldrb r0, [r0, #0x0]
                c.r[2] = c.r[1].wrapping_add(0); // 814fe10: add r2, r1, #0
                c.r[2] = c.r[2].wrapping_add(0x2e); // 814fe12: add r2, #0x2e
                c.st8(c.r[2], c.r[0]); // 814fe14: strb r0, [r2, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe16: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe18: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe1a: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe1c: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FE20` (0x0814fe20, thumb)
pub fn sub_814FE20(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe20;
    loop {
        match pc {
            0x0814fe20 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe20: ldr r0, [r1, #0x40]
                c.r[0] = c.ld8(c.r[0]); // 814fe22: ldrb r0, [r0, #0x0]
                c.r[2] = c.r[1].wrapping_add(0); // 814fe24: add r2, r1, #0
                c.r[2] = c.r[2].wrapping_add(0x2f); // 814fe26: add r2, #0x2f
                c.st8(c.r[2], c.r[0]); // 814fe28: strb r0, [r2, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe2a: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe2c: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe2e: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe30: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FE34` (0x0814fe34, thumb)
pub fn sub_814FE34(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe34;
    loop {
        match pc {
            0x0814fe34 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe34: ldr r0, [r1, #0x40]
                c.r[2] = c.ld8(c.r[0]); // 814fe36: ldrb r2, [r0, #0x0]
                c.st8(c.r[1].wrapping_add(0x1e), c.r[2]); // 814fe38: strb r2, [r1, #0x1e]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe3a: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe3c: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe3e: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FE40` (0x0814fe40, thumb)
pub fn sub_814FE40(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe40;
    loop {
        match pc {
            0x0814fe40 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe40: ldr r0, [r1, #0x40]
                c.r[2] = c.ld8(c.r[0]); // 814fe42: ldrb r2, [r0, #0x0]
                c.st8(c.r[1].wrapping_add(0x1f), c.r[2]); // 814fe44: strb r2, [r1, #0x1f]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe46: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe48: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe4a: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FE4C` (0x0814fe4c, thumb)
pub fn sub_814FE4C(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe4c;
    loop {
        match pc {
            0x0814fe4c => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe4c: ldr r0, [r1, #0x40]
                c.r[0] = c.ld8(c.r[0]); // 814fe4e: ldrb r0, [r0, #0x0]
                c.r[2] = c.r[1].wrapping_add(0); // 814fe50: add r2, r1, #0
                c.r[2] = c.r[2].wrapping_add(0x26); // 814fe52: add r2, #0x26
                c.st8(c.r[2], c.r[0]); // 814fe54: strb r0, [r2, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe56: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe58: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe5a: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe5c: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `sub_814FE60` (0x0814fe60, thumb)
pub fn sub_814FE60(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe60;
    loop {
        match pc {
            0x0814fe60 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe60: ldr r0, [r1, #0x40]
                c.r[0] = c.ld8(c.r[0]); // 814fe62: ldrb r0, [r0, #0x0]
                c.r[2] = c.r[1].wrapping_add(0); // 814fe64: add r2, r1, #0
                c.r[2] = c.r[2].wrapping_add(0x27); // 814fe66: add r2, #0x27
                c.st8(c.r[2], c.r[0]); // 814fe68: strb r0, [r2, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe6a: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe6c: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe6e: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe70: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `nullsub_23` (0x0814fe74, thumb)
pub fn nullsub_23(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe74;
    loop {
        match pc {
            0x0814fe74 => {
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe74: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

