// Generated by recomp from the ROM. Do not edit.
use crate::*;
use gba_rt::*;

/// `sub_814FE60` (0x0814fe60, thumb)
pub fn sub_814FE60(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe60;
    loop {
        match pc {
            0x0814fe60 => {
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe60: ldr r0, [r1, #0x40]
                c.r[0] = c.ld8(c.r[0]); // 814fe62: ldrb r0, [r0, #0x0]
                c.r[2] = c.r[1].wrapping_add(0); // 814fe64: add r2, r1, #0
                c.r[2] = c.r[2].wrapping_add(0x27); // 814fe66: add r2, #0x27
                c.st8(c.r[2], c.r[0]); // 814fe68: strb r0, [r2, #0x0]
                c.r[0] = c.ld32(c.r[1].wrapping_add(0x40)); // 814fe6a: ldr r0, [r1, #0x40]
                c.r[0] = c.adds(c.r[0], 0x1); // 814fe6c: add r0, #0x1
                c.st32(c.r[1].wrapping_add(0x40), c.r[0]); // 814fe6e: str r0, [r1, #0x40]
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe70: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `nullsub_23` (0x0814fe74, thumb)
pub fn nullsub_23(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x0814fe74;
    loop {
        match pc {
            0x0814fe74 => {
                pc = c.r[14] & !1; if pc == ret { c.pc = pc; return; } continue; // 814fe74: bx lr
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

/// `off_81B9114` (0x081b9114, thumb)
/// PROBLEM: 0x081b9130: undefined instruction 0xb194
pub fn off_81B9114(c: &mut Cpu) {
    let ret = c.ret;
    let mut pc: u32 = 0x081b9114;
    loop {
        match pc {
            0x081b9114 => {
                c.st8(c.r[4].wrapping_add(0x7), c.r[0]); // 81b9114: strb r0, [r4, #0x7]
                c.r[5] = 0; // 81b9116: lsr r5, r2, #0x0
                c.st32(c.r[13].wrapping_add(0x2d0), c.r[0]); // 81b9118: str r0, [sp, #0x2d0]
                c.r[3] = 0; // 81b911a: lsr r3, r3, #0x0
                c.st32(c.r[13].wrapping_add(0x3ac), c.r[0]); // 81b911c: str r0, [sp, #0x3ac]
                c.r[3] = 0; // 81b911e: lsr r3, r3, #0x0
                c.r[4] = c.r[7] << 2; // 81b9120: lsl r4, r7, #0x2
                c.r[3] = 0x0000b192; // 81b9122: ldr r3, [pc, #0x2ec] // 0x081b9410
                c.r[5] = c.lsl_imm_c(c.r[7], 2); // 81b9124: lsl r5, r7, #0x2
                c.r[7] = lsl_reg(c.r[7], c.r[7]); // 81b9126: lsl r7, r7
                c.r[6] = c.ld8(c.r[7].wrapping_add(0x1e)); // 81b9128: ldrb r6, [r7, #0x1e]
                c.r[4] = c.subs(c.r[4], 0xe3); // 81b912a: sub r4, #0xe3
                c.st32(c.r[13].wrapping_add(0x1fc), c.r[4]); // 81b912c: str r4, [sp, #0x1fc]
                c.r[4] = c.asr_imm_c(c.r[7], 32); c.nz(c.r[4]); // 81b912e: asr r4, r7, #0x0
                c.undefined(0x081b9130); // 81b9130: .hword 0xb194
            }
            _ => return c.fallback(pc, ret),
        }
    }
}

